### ISSUE TITLE
Store an if…then…elseif…else operator  in the IM

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#101]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB2-4|UM|-|all
***

### Issue Description
Currently there is no possibility to store an if…then…elseif…else operator  in the IM (or I don’t know how to do it) because it can have a variable number of elseif clauses.

### Proposed Solution
Improve the IM to be able to store this operator or add an explanatory example in case it is possible to store it.

**Comment by linardian** [comment]
Refers to old version of documentation,
