### ISSUE TITLE
The new artefact Described Value Domain is supplicated in the diagram

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#102]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB2-5|UM|-|all
***

### Issue Description
The new artefact Described Value Domain is supplicated in the diagram. 

### Proposed Solution
It should be called Code Item Relation in the diagram to be consistent with the explanation of the IM elements.

**Comment by linardian** [comment]
Refers to old version of documentation,
