### ISSUE TITLE
"Component expression"

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#103]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-1|RM|12|309
***

### Issue Description
"Component expression" is not specified before.

### Proposed Solution
specify what is a "component expression"

**Comment by capacma** [comment]
**Re-phrase the text:**
The VTL-ML Standard Library includes operators that may act on both Data Set and on Structure Components of the Data Sets. The last column shows if the Operator acts on Dataset, Components or both, when meaningful. The Component version takes as input and returns in output Component expressions. They are part of the syntax of other operators or clauses, where specifically required for row-wise processing
**with**
The VTL-ML Standard Library includes operators and functions that can be applied both to datasets and Structure Components of the datasets. The last column shows if the Operator acts on Dataset, Components or both, when meaningful.

**Comment by linardian** [comment]
Refers to old version of documentation,
