### ISSUE TITLE
They are part of the syntax of other operators or clauses, where specifically required for row-wise processing. 

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#104]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-2|RM|12|309
***

### Issue Description
They are part of the syntax of other operators or clauses, where specifically required for row-wise processing. 

### Proposed Solution
 It is no clear the subject, clarify the sentence.

**Comment by capacma** [comment]
Linked to #103

**Comment by linardian** [comment]
Refers to old version of documentation,
