### ISSUE TITLE
Single data points operators and functions.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#106]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-3|RM|13|318
***

### Issue Description
Single data points operators and functions
  
### Proposed Solution
Specify what is a single data point operator or function, is it an operator that can be applied to single row?

**Comment by capacma** [comment]
**Replace:**
Most of the single data points operators and functions can be applied to both Datasets and scalar values. The operands of the operators and functions can take the following forms:
**with:**
A single data point operator or function is a function that is applied to a single data point or scalar value and returns a single data point or scalar value (instead, a set operator or function is applied to a set of data points and returns a set of data points).
The operands of the single data point operators and functions can take the following forms:

**Comment by linardian** [comment]
Relates to an old version of documentation.
