### ISSUE TITLE
The sentence:" In this case the operator or function is applied to the specified measure or attribute." is a repetition with the column “conputation rule”.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#107]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-4|RM|13|322
***

### Issue Description
The sentence:" In this case the operator or function is applied to the specified measure or attribute." is a repetition with the column “conputation rule”.

### Proposed Solution
keep only one

**Comment by capacma** [comment]
Proposal: delete the text "In this case the operator or function is applied to the specified measure or attribute."

**Comment by linardian** [comment]
Relates to an old version of documentation.
