### ISSUE TITLE
The sentence "In this case the operator or function is applied to all measures of the Dataset having the data type accepted by the operator."

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#108]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-5|RM|13|324
***

### Issue Description
The sentence "In this case the operator or function is applied to all measures of the Dataset having the data type accepted by the operator."

### Proposed Solution
keep only one

**Comment by capacma** [comment]
Keep the text as it is. In fact the table at page 13 describes the binary operators and functions, and does not cover the case of unary operators and functions.
