### ISSUE TITLE
Remove references to possible VTL tools

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#11]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
BDI-4|UM|44|44-xx
***
In the User manual there are descriptions which refer to the possible VTL tools and their implementations more than to user aspects of the language. E.g. lines 1490-1492  (tricks internal of the VTL)	
It would be better to move the consideration regarding the possible VTL implementations in another document, to make this document focused on the use of the language.The manual should be inspected to detect these cases and remove them.

**Comment by bellomarini** [comment]
I confirm the comment and also suggest to group in the *technical manual* also some complex topics from the core.

**Comment by amattioc** [comment]
The "clever tricks" sentence is no longer present in 2.0 manual, anyway the suggesiton for a review still makes sense

**Comment by linardian** [comment]
VTL 2.1 will contain a technical manual
