### ISSUE TITLE
Specificatin of "ident"

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#112]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-10|RM|24|443
***

### Issue Description
It is not clear what is "ident"

### Proposed Solution
specify it

**Comment by bellomarini** [comment]
pag. 46 UM, identifiers. We should clarify when we refer to these identifiers and in general, maybe, eliminate the distinction between identifiers and references. To be discussed.

**Comment by linardian** [comment]
Refers to old version of documentation
