### ISSUE TITLE
codeDescr : constant 

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#113]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-12|RM|24|449
***

### Issue Description
codeDescr : constant 

### Proposed Solution
change with:  codeDescr : string

**Comment by bellomarini** [comment]
Agree.

**Comment by linardian** [comment]
To be considered if introducing define ValueDomain operator

**Comment by linardian** [comment]
Refers to old version of documentation
