### ISSUE TITLE
The sentence: "…...new ValueDomain is enumerated . "

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#114]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-13|RM|24|458
***

### Issue Description
The sentence: "…...new ValueDomain is enumerated . "

### Proposed Solution
Specify what is enumerated

**Comment by bellomarini** [comment]
@vignola already fixed?

**Comment by linardian** [comment]
Refers to old version of documentation
