### ISSUE TITLE
The restriction " … " should be specified or should be specified the rule to clearly know which type of restrictions can be applied.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#115]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-15|RM|24|471
***

### Issue Description
The restriction " … " on date, should be better specified or should be specified the rule to clearly know which type of restrictions can be applied

### Proposed Solution
 The "…" should be clearly specified

**Comment by bellomarini** [comment]
It looks like the current specification of restrictions on dates is not correct. A date data type always has year, month, day and so on and cannot be year-only, month-only or day-only.
I suggest to allow just date intervals as restrictions, for example as follows:

```restrict between 2012-12-31 and 2017-12-31```

**Comment by linardian** [comment]
Refers to old version of documentation
