### ISSUE TITLE
Specification of multi value domain & examples.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#116]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-17|RM|24|484
***

### Issue Description
Specify better how to obtain a multi value domain, provide examples.

**Comment by bellomarini** [comment]
To be discussed. What to do with multi-dimensional ValueDomains? Should they be supported in the VTL-DDL? Discuss with Vincenzo.

**Comment by linardian** [comment]
Multi-dimensional value domains (list/arrays) will be probably taken in consideration when valid use cases will arise
