### ISSUE TITLE
POSIX Description.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#119]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-20|RM|24,26|468,552
***

### Issue Description
POSIX it is not very common for statisticians

### Proposed Solution
insert a note that descripe it and where to find some materials (like at page 99 of the RM)

**Comment by bellomarini** [comment]
Ok, I suggest the following common reference:
http://www.regular-expressions.info/posix.html

**Comment by linardian** [comment]
See if a note is needed on POSIX
