### ISSUE TITLE
Sentences with bad grammar

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#121]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-13|RM|26|499-501
***

### Issue Description
“..are implicitly specified with him…”, etc.:.Sentences with bad grammar.

### Proposed Solution
Correct grammar

**Comment by bellomarini** [comment]
I suggest to rephrase as follows:

Whenever a multi-dimensional ValueDomain is specified, all the possible combinations of mono-dimensional ValueDomains are implicitly specified as well.

**Comment by linardian** [comment]
Refers to an old version of documentation.
