### ISSUE TITLE
in-line CodeList cannot be reused. 

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#122]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-19|RM|24,26|462,546
***

### Issue Description
An in-line CodeList cannot be reused. 

### Proposed Solution
why? It could be used to reuse it once it is defined. This is also in contraddiction with the sentence at line 572 and with the fact that the valude Domain can be used for the dataStructure. This should be  clarified better.

**Comment by bellomarini** [comment]
The idea is that if a CodeList is defined in-line, it cannot be reused because it does not have an explicit name. This is the general rationale to distinguish reusable vs non-reusable cases. Why is it in contradiction with line 572?
