### ISSUE TITLE
DefineVariable contains no semantic specification or example

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#123]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-14|RM|28|634
***

### Issue Description
DefineVariable contains no semantic specification or example

### Proposed Solution
Provide semantic specification and example to clarify usage.

**Comment by bellomarini** [comment]
*Semantics*

It defines a new variable in the Information Model, named after variableId. If the variable is already existing, it has no effects.

*Example*

```define variable population```

**Comment by linardian** [comment]
Refers to old version of documentation
