### ISSUE TITLE
Incomplete Sentence "Its identifier, VariableId, is automatically and …."

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#127]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-24|RM|28|706
***

### Issue Description
The sentence: "Its identifier, VariableId, is automatically and …." seems incomplete, what is the value of the VariableId?

### Proposed Solution
Complete the sentence

**Comment by bellomarini** [comment]
For each component a new RepresentedVariable is created (or an existing one is reused). Its identifier,
706 VariableId, is automatically and the respective property of DataStructureComponent is assigned accordingly. 

I suggest to rephrase as follows:

If the respective RepresentedVaraible does not exist, for each component, one is created automatically, using VariableId as its default identifier.
