### ISSUE TITLE
Typo in DataStructureRef

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#129]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-26|RM|29|744,747
***

### Issue Description
DataStructureRef : dataStructure-ref; valueDomainSubsetRef : valueDomainSubset-ref

### Proposed Solution
It is not instead dataStructureRef : ident; valueDomainSubsetRef : ident?

**Comment by linardian** [comment]
Refers to old version of documentation,
