### ISSUE TITLE
"dataStructure_of_datasetId_description" in the IM.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#131]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-28|RM|30|794
***

### Issue Description
I did not find the "dataStructure_of_datasetId_description" in the IM.

### Proposed Solution
Include in the IM.

**Comment by bellomarini** [comment]
I agree with the proposed solution, though defining a specific description for each Data Structure could be verbose for the user. The paragraph meant to suggest a default anyway. The explanation is not clear and has to be improved.

**Comment by linardian** [comment]
Refers to old version of documentation
