### ISSUE TITLE
Structure Component

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#132]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-30|RM|30|804
***

### Issue Description
Structure Component does not exists.

### Proposed Solution
Change with component. Does the structure component is equal to data structure componet?

**Comment by bellomarini** [comment]
Yes, simply ``Component'' is better.

**Comment by linardian** [comment]
Refers to old version of documentation
