### ISSUE TITLE
Explain data point ruleset.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#136]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-35|RM|32|897
***

### Issue Description
The sentence "….when used fordata filtering…." introduce something that it is unknown to the reader.

### Proposed Solution
Explain that the data point ruleset can be used before to say: when used for data filtering…… for example saying: the data point ruleset can be used with the check operator........and with the filter operator...

**Comment by linardian** [comment]
Refers to old version of documentation,
