### ISSUE TITLE
The sentence "When the Ruleset is used for validation…." contains some information repeted and some that should be inside the "return" item.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#139]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-38|RM|33|from 917 to 923
***

### Issue Description
The sentence "When the Ruleset is used for validation…." contains some information repeted and some that should be inside the "return" item.

### Proposed Solution
Remove the repeted information and move part of the sentence that explain columns returned to the return item.

**Comment by linardian** [comment]
When the Ruleset is used for validation
