### ISSUE TITLE
Condition on other dimensions (other than time). Condition on the rule dimension:

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#141]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-12|RM|34|Vertical ruleset - conditions
***

### Issue Description
Condition on other dimensions (other than time). Condition on the rule dimension:

### Proposed Solution
Provide example of needs.To be expressed as "dim = XX" in the when clause, where dim is the rule dimension. Small change in the manual

**Comment by capacma** [comment]
The condition on other dimensions is allowed and this issue can be closed.
