### ISSUE TITLE
In the sentence: "It specifies the space on which the Ruleset is defined. " it is not clear what is the "space".

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#142]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-40|RM|35|1026
***

### Issue Description
In the sentence: "It specifies the space on which the Ruleset is defined. " it is not clear what is the "space".

### Proposed Solution
Clarify

**Comment by linardian** [comment]
Refers to old version of documentation
