### ISSUE TITLE
MapTo and MapFrom

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#148]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
EG-1|RM|39|Map (Transcode) and Define mapping
***

### Issue Description
MapTo and MapFrom should not be identifiers as it might be required to have duplicated values. Real examples would require two codes to be combined in a single one or vice-versa. Example: Recoding ISIC4 codes at 2 digit level (Division) into level 1 (Section); Divisions 01-03 recodes into Section A, 05-09 into B, 10-33 into C, etc.. For splitting a code "from" into two or more in "to" additional information would be required in the condition, but attributes may provide such information and allow for splitting codes.

### Proposed Solution
Open

**Comment by linardian** [comment]
Refers to old version of documentation
