### ISSUE TITLE
Makes the syntax equal as in the other operators (comp : Dataset component-ref).

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#151]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-48|RM|42|1403
***

### Issue Description
Makes the syntax equal as in the other operators (comp : Dataset component-ref).

### Proposed Solution
change to comp : component-ref.

**Comment by linardian** [comment]
Refers to old version of documentation
