### ISSUE TITLE
The sentence: "If there is at least one aggrPart, there must be one for each Measure Component that is present in a keepPart"

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#162]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-56|RM|46|1543
***

### Issue Description
The sentence: "If there is at least one aggrPart, there must be one for each Measure Component that is present in a keepPart" it is not necessary, what is important is to specify that only the measures in the aggr part will be retrieved.

### Proposed Solution
Change the sentence.

**Comment by linardian** [comment]
Refers to old version of documentation
