### ISSUE TITLE
Modification of keep clause.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#163]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-57|RM|46|1549
***

### Issue Description
If the keep can be applied also to identifiers, than the set of identifiers component can be less than those of the input dataset.

### Proposed Solution
Modify if keep (in get operator) can be used also with identifiers otherwise modify the description of the keep clause.

**Comment by linardian** [comment]
Refers to old version of documentation
