### ISSUE TITLE
Merge the component and dataset sections in a single section, for all operators and functions.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#164]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-21|RM|50|Merge component and dataset sections
***

### Issue Description
Merge the component and dataset sections in a single section, for all operators and functions.

### Proposed Solution
Open

**Comment by capacma** [comment]
The component and dataset sections have been merged into a single section in VTL 1.1. 
Therefore we can close this issue.
