### ISSUE TITLE
Dataset alias

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#165]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-29|RM|50|Join expression
***

### Issue Description
We should add the dataset alias otherwise it is not possible to join the same dataset to itself (this is useful when the join is performed on a partial key)

### Proposed Solution
Change line 1735 as follows: 
join_clause := { [ inner | outer | cross ] } { ds { **as** alias } { , ds { **as** alias } } * on dim { , dim } * }

**Comment by capacma** [comment]
Discussed in Luxembourg: change line 1735 as follows:
 join_clause := join_type ( { ds { **alias** ds2 } { , ds { **alias** ds2 } } *  } )
