### ISSUE TITLE
Specify the notation "Underlined word" represents.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#166]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-58|RM|51|1735
***

### Issue Description
The notation that a underlined word (for inner) represents a default is not specified.

### Proposed Solution
Specify it in the introductory part of the RM and use for the other operators.

**Comment by linardian** [comment]
Referes to an old version of documentation
