### ISSUE TITLE
Specify "alias" parameter in syntax.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#170]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-16|RM|52|1748-1755
***

### Issue Description
The “alias” parameter seems to be missing from the syntax specification.

### Proposed Solution
Include alias in specification of parameter ds. Provide example use of alias.

**Comment by capacma** [comment]
This issue can be closed (continue to work on #165)
