### ISSUE TITLE
Filter application in more than one ruleset.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#175]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-4|RM|55|Filter, 55, 166
***

### Issue Description
Decision if the Filter is able to apply more than one ruleset.

### Proposed Solution
Reflect on more than 1 ruleset, Maybe: no problem. Row is kept in the result if all rules of all rulesets evaluate to true. When errorlevel = warning the row is not kept in the result when the condition evaluates to false.

**Comment by capacma** [comment]
This issue has been created before we drafted VTL 1.1.
In VTL 1.1 we have decided to apply filter only to components.
This issue can be close.
