### ISSUE TITLE
Syntax - Semicolon separator character.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#176]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-17|RM|55|1870-1871-1872
***

### Issue Description
The example VTL code uses a semicolon as statement separator. This does not seem to be according to the syntax specification.

### Proposed Solution
Remove use of semicolon as separator character.

**Comment by capacma** [comment]
This issue is also described in #177, I propose to close it and continue the work on #177.
