### ISSUE TITLE
Syntax - Semicolon separator character - 2nd.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#177]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-18|RM|55|1874-1875
***

### Issue Description
The example VTL code uses a semicolon as clause separator. According to the syntax specification this should be a comma.

### Proposed Solution
Replace semicolon with comma in example code.

**Comment by capacma** [comment]
This issue is also described in #174, I propose to close it and continue the work on #174.
