### ISSUE TITLE
Syntax:  unfold d, m { to … }

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#178]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-44|RM|56|unfold 
***

### Issue Description
Syntax:   unfold d, m { to … },when the to part is missing then it is equivalent to (all values of m) include order asc/desc?

### Proposed Solution
Allow syntax: unfold d, m { to … }

@capacma
use **pivot** instead of **unfold** and **unpivot** instead of **fold**.

**Comment by linardian** [comment]
Referes to an old version of documentation
