### ISSUE TITLE
More examples of how to apply functions in the VTL context.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#183]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB-23|RM|58|2057
***

### Issue Description
It would be very helpful to provide more examples of how to apply functions in the VTL context.  It would, for example, be interesting to have an example where a function is applied to rows of a dataset to create some new information (in the form of a new column).

### Proposed Solution
For example: a function distanceInTwoDimensions: create function distanceInTwoDimensions(x as Numeric, y as Numeric) (returns Numeric sqrt(x*x=y*y)) applied to a data set (“coordinates”) of the structure {coordinateId, x, y} with data {{1, 3, 4}, {2, 5, 12}, {3, 8, 15}}. Therefore the line coordinates := coordinates [calc distanceInTwoDimensions(x, y) as z role MEASURE] should create a resulting data set having the following structure {coordinateId, x, y, z} with values {{1, 3, 4, 5}, {2, 5, 12, 13}, {3, 8, 15, 17}}.

**Comment by linardian** [comment]
Referes to an old version of documentation
