### ISSUE TITLE
ds_1 (wrong result dataset name)

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#184]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB-15|RM|59|2110
PL-GOV-7|RM|59|2110
***

### Issue Description
ds_1 (wrong result dataset name)

### Proposed Solution
ds_r

**Comment by egreising** [comment]
The proposed solution is correct

**Comment by linardian** [comment]
Refers to old version of documentation
