### ISSUE TITLE
Mistakes in examples of “substr” operator

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#187]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-CSO-27|RM|62|2270
***

### Issue Description
There are mistakes in examples of “substr” operator.

### Proposed Solution
"lo, world!" -> "llo, world!", "lo, w" -> “llo, ”,"rld" -> “orld”

**Comment by egreising** [comment]
The proposed solution is correct.

**Comment by linardian** [comment]
Refers to old version of documentation
