### ISSUE TITLE
Rendering issue.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#188]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB-16|RM|64|2284-2285
***

### Issue Description
Rendering issue.

**Comment by egreising** [comment]
There's an issue with the table representing dataset ds_r. Can be fixed copying the table ds_1, renaming to ds_r and modifying M1 to "hello". The remove the problematic table.

**Comment by linardian** [comment]
Refers to old version of documentation
