### ISSUE TITLE
The sentence is a repetition of the sentence 2347.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#190]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-65|RM|64|2312
***

### Issue Description
The sentence is a repetition of the sentence 2303.

### Proposed Solution
Remove the sentence.

**Comment by egreising** [comment]
I can't see the repetition.
Linked to #

**Comment by linardian** [comment]
Refers to old version of documentation
