### ISSUE TITLE
Examples have date patterns different from definition of operator date_from_string.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#191]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-GOV-8|RM|66,67|2334-2377
***

### Issue Description
Examples have date patterns different from definition of operator date_from_string.

### Proposed Solution
Correct to proper format.

**Comment by egreising** [comment]
Correct the examples once the date formats and related operators have been defined. Linked to #245  and #280

**Comment by linardian** [comment]
Refers to old version of documentation
