### ISSUE TITLE
ds_1 (wrong result dataset name)

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#192]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-GOV-10|RM|70|2470,2480
***

### Issue Description
ds_1 (wrong result dataset name)

### Proposed Solution
ds_2

**Comment by fewagener** [comment]
Change the name of the result dataset from ds_1 to ds_2. It applies to the examples 2) and 3)
