### ISSUE TITLE
“…has these common string measures…” should be “…has these common numeric measures…”

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#193]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-19|RM|71|2510
***

### Issue Description
“…has these common string measures…” should be “…has these common numeric measures…”

### Proposed Solution
Replace accordingly

**Comment by fewagener** [comment]
Replace word string by numeric in line 2510 of RM.
