### ISSUE TITLE
“…listsum than returns…” change sentence

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#194]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-20|RM|71|2518
***

### Issue Description
“…listsum than returns…” should be “…listsum that returns…”

### Proposed Solution
Replace accordingly

**Comment by fewagener** [comment]
Replace 'than' by 'that' in line 2518 of RM
