### ISSUE TITLE
“…containing the algebraic sum or subtraction…”  change sentence

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#195]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-21|RM|73|2574-2575
***

### Issue Description
“…containing the algebraic sum or subtraction…” should be “…containing the algebraic product or ratio…”

### Proposed Solution
Replace accordingly

**Comment by fewagener** [comment]
Replace 'sum or substraction' with 'product or ratio'in line 2574 of RM
