### ISSUE TITLE
Definition of  [round(ds, decimals) | ceil(ds) | floor(ds)] operator:   decimals – must be an integer greater or equal than zero.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#197]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-GOV-11|RM|74|2612
***

### Issue Description
Definition of  [round(ds, decimals) | ceil(ds) | floor(ds)] operator:   decimals – must be an integer greater or equal than zero.

### Proposed Solution
Why not:  decimals – can be an integer greater or equal than zero or less than zero. For instance A:=round(123.4, -2) resulting in A=100

**Comment by fewagener** [comment]
I think the proposal makes sense. Other languages have also the possibility of rounding before the comma (limiting the precision of the value). So, I would change the sentence from 'must be an integer greater or equal than zero' to 'must be an integer'. But I think we have to adapt the Parameters and Semantic specification avoiding the constraint to decimal places.
