### ISSUE TITLE
Syntax - Dataset Mandatory

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#200]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-68|RM|84,115,118|3029
***

### Issue Description
In the syntax seems that only one dataset is mandatory. Is this the case or at least two datasets must be mandatory?

### Proposed Solution
Add a dataset mandatory in the syntax (using for example the same notation than those used in the addition,etc…), if needed

**Comment by fewagener** [comment]
Laura, can you please specify which operator you are referring to? I can't find the problem.

**Comment by vignola** [comment]
This issue should be assigned to numeric and set  operators.
For numeric is about the listsum that represents the sum between two datasets while in the sintax seems that only one is mandatory. 
For  set operators, it concernes the union and intersect operator in which the syntax  foreseen only one mandatory dataset.

**Comment by fewagener** [comment]
About listsum, I understand that if the operator has only one input dataset, it would return the same dataset but changing all missing values with zero. (listsum is in line 2989)

**Comment by linardian** [comment]
Referes to an old version of documentation
