### ISSUE TITLE
Constraints on identifiers.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#201]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-69|RM|84|3037
***

### Issue Description
Are there any constraints on the identifiers of the datasets as mentioned for other operators actini on more than one datasets

### Proposed Solution
Add, if needed ì, constraints on identifiers

**Comment by fewagener** [comment]
I have changed the label as it affects a boolean operator. Anyway, I would need more information because I haven't understood the issue.

**Comment by vignola** [comment]
The issue is always on listsum.
The only constraint of the operator is that the input datasets have numeric measures and there are no constrains  on the identifiers of  the input datasets. 
These should be added.

**Comment by fewagener** [comment]
I agree with you. They should be added in line 3003.

**Comment by linardian** [comment]
Referes to an old version of documentation
