### ISSUE TITLE
"in, not in" applicable to all types of components.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#202]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-42|RM|90|in, not in  
***

### Issue Description
Applicable to all components (not limited to measures as in current reference manual)

### Proposed Solution
Allow in, not in to be applied to all types of components

**Comment by linardian** [comment]
Referes to an old version of documentation
