### ISSUE TITLE
Bahaviour of "A between B and C".

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#203]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
DI-4|RM|91|Boolean operators and functions p. 91
***

### Issue Description
The behaviour of between is not consistent with the behaviour of the relational operators. Construct "A between B and C" should be synonymous to "A >= B and C <= A".

### Proposed Solution
Make the description  of A between B and C consistent with the behaviour of A >= B and C >= A.

**Comment by vignola** [comment]
After the meeting in Rome and in accordance with the issue, a proposal for the returned dataset can be:

Returns

If ds_1 is a scalar then between returns a Boolean assuming value true (false) if  ds_1 is (not) greater or equal than  ds_2 and (not) less or equal than ds_3.
If ds_1 is a Dataset then operator returns a Dataset having the Identifier Components 
of ds_1 and one  Boolean measures having the name .....  and  assuming value true (false) if  ds_1 is (not) greater or equal than  ds_2 and (not) less or equal than.

**Comment by capacma** [comment]
As mentioned in the proposed solution I propose the following definition:
A between B and C is equivalent to A >= B and C >= A
maybe this definition is clear enough and we do not need to provide any further explanation.

**Comment by vignola** [comment]
you mean without distinguish between scalar and dataset and without to specify what is the result in terms of Identifiers and measure?
