### ISSUE TITLE
In constraints, the sentence "if ds is a dataset, all Measures..." is too strict.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#204]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-71|RM|91,112,113|
***

### Issue Description
In constraints, the sentence "if ds is a dataset, all Measures..." is too strict.

### Proposed Solution
Replace "all" with "at least one"

**Comment by vignola** [comment]
This has been solved during the meeting in Rome with the rule that the input datasets must have only measures accepted by the operator.
The description must remain as it is: "if ds is a dataset, all Measures..."
The issue can be closed.
