### ISSUE TITLE
No ds in the syntax.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#205]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-72|RM|91|3291
***

### Issue Description
In Returns is reported ds but there is no ds in the syntax.

### Proposed Solution
Replace with one of the dataset used in the syntax.

**Comment by capacma** [comment]
replace ds with ds_1

**Comment by vignola** [comment]
Merge this issue with the #203
