### ISSUE TITLE
Review example. All data points in urbanization_rate exist in population.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#207]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB-17|RM|94|3369
***

### Issue Description
Review example. All data points in urbanization_rate exist in population.

**Comment by fewagener** [comment]
I would adapt urbanization_rate to keep the current result. There is also a typo in example 4.
In the Return section I would add common: A Dataset with all **common** Identifier Components of the two Datasets and ...

**Comment by vignola** [comment]
This issue is the same than #306. The issue can be closed.

**Comment by linardian** [comment]
Refers to old version of documentation
