### ISSUE TITLE
Explan - key runs for the operator exist_in, not_exist_in, when the identifiers of the two datasets are not the same.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#208]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-74|RM|94|
***

### Issue Description
It is not very clear how the matching of the key runs for the operator exist_in, not_exist_in, when the identifiers of the two datasets are not the same but they only have one identifier in common.

### Proposed Solution
Explain better and provide examples of this case.

**Comment by vignola** [comment]
After the meeting in Rome this is not allowed anymore because the dataset must have the same Identifiers or one must have the superset of identifiers.

I think issue this can be closed
