### ISSUE TITLE
Boolean measurement components.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#209]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
DI-8|RM|99|all p. 99
DI-9|RM|99|all, any, unique p. 99
***

### Issue Description
(DI-8) The syntax, the description, and the examples of all do not match each other. According to the example, not all values in the dataset are checked, only Boolean measurement components.
(DI-9) Operators all, any, and unique always return a Boolean, a true or false. As such, the result would be useful as e.g. if condition. However, the RefMan says these operators return single-row datasets with a single Boolean column named 'CONDITION'.  This looks unnecessarily complex.

### Proposed Solution
(DI-8) Correctly specify that all checks that values of all Boolean measurement components in the argument dataset are true.
(DI-9) Make all, any, unique return Boolean instead of dataset.

**Comment by vignola** [comment]
DI-8 the examples must be corrected
DI-9 to my knowledge a boolean is not possible to return a boolean from a dataset but only a dataset having only one measure assuming a booean value

**Comment by linardian** [comment]
Refers to old version of documentation
