### ISSUE TITLE
Constraints & operators in boolean measure.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#211]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-75|RM|99,100,101|
***

### Issue Description
In constraints, the fact to apply these operators to more than one boolean measure implys that the measures must be related between them with and or or operator, to return only one value.

### Proposed Solution
I suggest to apply these operatos to only one boolean measure.

**Comment by vignola** [comment]
This issue as been solved after the meeting in Rome in which as been decided that all the boolean operators can be applied to only one boolean measure.
I think is can be closed
