### ISSUE TITLE
Invalid Examples for 2 and 3 referring to operators “any” and “unique”

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#212]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-CSO-28|RM|101|3505, 3509,  3544, 3548
***

### Issue Description
Examples 2 and 3 for operators “any” and “unique” are the same but with different results.

### Proposed Solution
Remove or correct invalid examples.

**Comment by vignola** [comment]
The comment is the same of #309 issue for _unique_ operator. For _any_ operator the example 3 must be modified.
I propose the following one:
3) ds_2 := any (ds_1.VALUE_2000>20 AND ds_1.VALUE_2001>60)

ds_1

GENDER 	|VALUE_2000	|VALUE_2001
|:--|:--|:--
M	|200		|90
F	|50	|120

ds_2 

CONDITION
|:--
TRUE
