### ISSUE TITLE
Arguments explanation

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#214]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
DI-12|RM|104|and, or, xor, not (and many others)
***

### Issue Description
The description of the arguments uses the structure specification enclosed in square brackets. Inside there is a pipe ("|") separating the dataset part from type Boolean. This is not a valid type in VTL, and if it is meant to represent a type pattern, it looks improvised (it is not defined) and obscures more than it clarifies. One of the key requirements, that the two datasets must be joinable, is not even mentioned.

### Proposed Solution
Explain arguments in a more natural and readable form, e.g. for and: Parameters: ds_1: a Boolean or a dataset,ds_2: a Boolean or a dataset. Constraints:If ds_1 is a dataset, it needs to have at least one Boolean measure. The same holds for ds_2, If both ds_1 and ds_2 are datasets, they have to be joinable, i.e., all identifiers of ds_1 must also be (in name and type) in ds_2 or vice versa.

**Comment by linardian** [comment]
Refers to an old version of documentation
