### ISSUE TITLE
The parameter name ds_1 is not used in the text (ds is used instead). ds is allowed to be a string (instead of Boolean).

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#217]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
DI-13|RM|109|not p. 109
***

### Issue Description
The parameter name ds_1 is not used in the text (ds is used instead). ds is allowed to be a string (instead of Boolean).

### Proposed Solution
Fix the errors.

**Comment by vignola** [comment]
The issue is related to the not operator. 
replace ds_1 with ds in the _syntax_ instead and string with boolean in _parameters_
