### ISSUE TITLE
Syntax for optional named parameters: dedup: F

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#221]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
DI-14|RM|114|union, intersect p. 114, 117
***

### Issue Description
The syntax for union and intersect does not follow the standard for optional named parameters in a function call. The final optional parameter has the form dedup(F), whose normal meaning is "the result of calling function named dedup with argument F."

### Proposed Solution
Use correctly the syntax for optional named parameters: dedup: F.

**Comment by linardian** [comment]
Refers to an old version of documentation
