### ISSUE TITLE
In Semantic Specification the last sentence "If only a dataset..." has no meaning with the union operator.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#222]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-77|RM|114|3889
***

### Issue Description
In Semantic Specification the last sentence "If only a dataset..." has no meaning with the union operator.

### Proposed Solution
remove the sentence.

**Comment by linardian** [comment]
Refers to an old version of documentation
