### ISSUE TITLE
Review example, the result table is not correct (and should be named ds_r).

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#223]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB-20|RM|115|3901
***

### Issue Description
Review example, the result table is not correct (and should be named ds_r)

**Comment by vignola** [comment]
this is the same issue than #224

**Comment by fewagener** [comment]
Absolutely. Actually the four examples are run-time errors because no consResFunction is specified in any of them and the result would have duplicates. All of them should be reviewed, we should use consResFunction in some examples.
