### ISSUE TITLE
In the reference manual  intersect is allowed to have no dedup clause: in this case the result contains (automatically) the measures of the first operand.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#225]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-47|RM|117|intersect 
***

### Issue Description
In the reference manual  intersect is allowed to have no dedup clause: in this case the result contains (automatically) the measures of the first operand.

### Proposed Solution
Intersect : indicate that when dedup clause is missing then the  result contains the measures of the first operand.

**Comment by linardian** [comment]
Refers to an old version of documentation
