### ISSUE TITLE
Aggregate/Rulesets

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#227]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-5|RM|123|Aggregate 123-130
***

### Issue Description
Decision if the Aggregate is able to apply more than one rulesets.

### Proposed Solution
Apply to more than 1 ruleset at the same time with other operators.

**Comment by linardian** [comment]
I think this issue is non valid anymore, being aggregate no more and operator. So I propose to close it.
