### ISSUE TITLE
Datapoints

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#230]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-78|RM|123|
***

### Issue Description
Which datapoints are returned? only those transcoded or also the not trancoded ones. In the second case there could be duplication (if a new code already exist into the datset).

### Proposed Solution
Specify better, avoiding the second option.

**Comment by linardian** [comment]
Refers to an old version of documentation
