### ISSUE TITLE
Syntax - "parentheses" () in group by and along list.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#231]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-32|RM|127|Aggregate functions
***

### Issue Description
Add parentheses () in group by and along list otherwise there can be a problem of syntax.

### Proposed Solution
Add parentheses () in group by and along list.

**Comment by linardian** [comment]
Refers to old version of documentation
