### ISSUE TITLE
Add Error Message / Could be task for the TF Validation.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#240]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-2|RM|149|Error code and error message
***

### Issue Description
Reflect on the introduction of an error message.The error code may be difficult to exchange between organizations. Use Severity or errorlevel (Could be a  task for the TF Validation?)

### Proposed Solution
Add errormessage? Choose between Severity or errorlevel  and if its datatype is string or number, then verify that these keywords and related datatypes are equal in both documents.

**Comment by egreising** [comment]
The capacity of outputting a free text message by means of a clause would be very useful for debugging purposes.
