### ISSUE TITLE
Syntax_Check_Dataset_Values

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#242]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-34|RM|149|check datapoint ruleset 
MC-35|RM|149|check datapoint ruleset
MC-36|RM|149|check
MC-38|RM|149|check_dataset_values
DI-15|RM|149|check p. 149-153
***

### Issue Description
(MC-34) Syntax is wrong: dpr + 
(MC-35) Not valid measures (wrong default).
(MC-36) The parser cannot say the type of check operator (single rule, hierarchical ruleset, horizontal ruleset).
(MC-38) Check_dataset_values  is not defined but used in check_value_domain.
(DI-15) The syntax for check (different versions) does not follow the standard for optional named parameters in a function call.  For instance, the normal reading of valid, all, condition, and measures is the value held in variables of the same name. The normal reading of not valid is the logical negation of the value held in variable valid. The normal reading of threshold(3) is the result of applying function threshold to integer argument 3.

### Proposed Solution
(MC-34) Replace dpr + with dpr { , dpr } *
(MC-35) Change the default to not valid and measures.
(MC-36) Introduce a way to differentiate the different types of check.
(MC-38) Remove check_dataset_values  or define it.
(DI-15) Use the optional named parameters, e.g.:include_invalid: Boolean default true, include_valid: Boolean default false, show_measures: Boolean default true, show_condition: Boolean default false, threshold: integer default 0 etc.  Example: check(ds, ruleset, include_valid: true, show_condition: true, threshold: 5).

**Comment by linardian** [comment]
Refers to an old version of documentation
