### ISSUE TITLE
Single Output dataset.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#243]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
BDI-16|RM|149|All
***

### Issue Description
Multiple checks / usability. If each ‘check’ on a single input dataset produces a single output dataset, the outcome of a check process could be a huge number of datasets. Pros & Cons: because each check output is a single dataset,  for each output information about structure is available, but at the same time, a huge number of datasets could be  difficult to process and also to represent say in a report or in an inquiry tool. 

### Proposed Solution
Evaluate the option to allow the production of single output dataset using a new ‘extended union’ operator (in this case the structure of each output will be missed).

**Comment by bellomarini** [comment]
The check operator should be extended so as to accept a number of boolean expressions.

```
check(expr1, expr2, ... exprN, [extra parameters])
```

* All the output Boolean Dataset must have the same Identifier Components.
* The output includes a supplementary identifier component (namely, "CONDITION_NUMBER"),
that specifies the validation the data point refers to.

Example:
```
check(ds1>5, ds1+ds2<6,ds1-ds4>ds5)
```


|ID1 | ID2 | CONDITION_NUMBER| COND| extra params |
|--|--|--|--| -- |
|1 | 2 | 1 | T| .. |
|1 | 2 | 2 | F| .. |
|1 | 2 | 3 | F| .. |
|2 | 2 | 1 | T| .. |
|2 | 2 | 2 | F| .. |
|2 | 2 | 3 | T | .. |
