### ISSUE TITLE
Component reference.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#244]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
DI-16|RM|154|check_value_domain_subset p. 154-155
DI-17|RM|154|check_value_domain_subset p. 154-155
DI-18|RM|154|check_value_domain_subset p. 154-155
DI-19|RM|156|check_value_domain_subset p. 156
***

### Issue Description
(DI-16) The second (optional) parameter is specified as a list of component references (type component-ref). There is no such type in VTL 1.1. Example 1 defines l_1 as:list<component-ref>(REF_AREA). Even if component-ref type existed in the type system, for this to make sense REF_AREA should be a (global) variable whose value is an instance of the component-ref type, not a name of the component in dataset ds_1.
(DI-17) Even if component-ref type existed in the type system, for this to make sense REF_AREA should be a (global) variable whose value is an instance of the component-ref type, not a name of the component in dataset ds_1.
(DI-18) It is impossible to distinguish the  second and the third parameters from looking at the expression: was the second given and the third skipped, or the second was skipped and the third given?
(DI-19) In Example 2, there is a mention of: list<valueDomain-ref>(D1, D2) while valueDomain-ref does not exist as a type in VTL 1.1.

### Proposed Solution
(DI-16) Make the second (optional) parameter of check_value_domain_subset should have type list<string> and its members should be strings naming the components in the dataset (the first parameter), not identifiers (which are normally interpreted as variable names).
(DI-17) The same solution as above applies.
(DI-18) Completely rewrite the syntax of check_value_domain_subset which is presently very confusing and does not conform to the standard for function calls.
(DI-19) D1 and D2 must be defined as global variables (coming from what module(s)?) whose values are value domain objects defined in the IM.

**Comment by linardian** [comment]
Refers to old version of documentation
