### ISSUE TITLE
Description of parameters/ Time Series.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#245]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
DI-20|RM|157|Fill_time_series p. 157
MC-14|RM|157|Date vs time period
BDI-25|RM|157|All
***

### Issue Description
(DI-20) The description of parameters is very complex, mostly repeated from one operator to another, and its point is very difficult to understand, e.g. for ds.
(MC-14) The functions working on time series should use the time information: Use date or time period,The reference manual must be corrected.
(BDI-25) The management of time dimension is unsatisfactory and seems to be designed on operator basis. For example, time series and time aggregate functions handle it differently. Time literals are sometimes specified with different formalisms. 

### Proposed Solution
(DI-20) Simplify the explanation, e.g.:ds: a dataset with at least one numeric measure component.
(MC-14)
(BDI-25) Propose a unique approach.
@capacma: see proposal in the comment below

**Comment by capacma** [comment]
The attached document contains a proposal for managing different formats for time_period

[time period.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/848358/time.period.docx)

**Comment by egreising** [comment]
_Trimester_ means "A period of three months", i.e. it is a synonym of _Quarter_. A period of four months is called "_**Quadrimester**_" (although it is a latinism not often used).

**Comment by egreising** [comment]
I agree with Maurizio's proposal. I would just add **yyyyA** as a valid format for annual, although accepting the omission of the A to default to Annual.

**Comment by capacma** [comment]
I agree with Edgardo that a trimester has a duration of 3 months. The mistake comes from a SDMX document https://sdmx.org/wp-content/uploads/SDMX_2-1-1-SECTION_6_TechnicalNotes-march-2013.pdf in which a trimester is defined as a period of 4 months:

Reporting Trimester:
Period Indicator: T
Period Duration: P4M (four months)
Limit per year: 3
Representation: common:ReportingTrimesterType (YYYY-Tt, e.g. 2000-T3)

Proposed solution: eliminate the "trimester" time period from the format.

**Comment by capacma** [comment]
OK to add yyyyA as a valid format for annual

**Comment by linardian** [comment]
Refers to old version of documentation
