### ISSUE TITLE
Redundant functions.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#246]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-24|RM|158|flow_to_stock, stock_to_flow, timeshift, 158-160
***

### Issue Description
Redundant functions: they can be expressed with analytic functions lad, sum etc.

### Proposed Solution
Remove  flow_to_stock, stock_to_flow, timeshift from VTL.

**Comment by linardian** [comment]
Refers to old version of documentation
