### ISSUE TITLE
Definition of named argument.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#247]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
DI-23|RM|160|Timeshift p. 160
***

### Issue Description
The syntax does not respect the standard for named arguments. The normal meaning of unit=A is a Boolean expression where the value of variable unit is compared to the value of variable A.

### Proposed Solution
Define named argument:unit: string with valid values "A", "M", "Q", "D".

**Comment by vignola** [comment]
In the syntax unit does not represent a variable but a keyword representing the unit of time to be shifted. However in the syntax the word "unit" seems to be mandatory while in the examples it is not.
This should be corrected.

**Comment by linardian** [comment]
Refers to old version of documentation
