### ISSUE TITLE
Syntax_Regarding the rename functionality & Redundant.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#249]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB-29|RM|166|5354
MC-25|RM|166|166-170 - clauses: rename, filter, keep, calc, attrcalc
***

### Issue Description
(ECB-29) There is a difference in the syntax regarding the rename functionality. Depending on the usage of the rename functionality in a join (rename clause) or just renaming a variable of a dataset is written in different ways (in case of a join the syntax is like ‘rename x to “y”’ while in the other case the syntax is like ‘rename x as “y”’). We strongly suggest to harmonize the syntax.
(MC-25) Redundant: they can be expressed with the join expression clauses.

### Proposed Solution
(ECB-29)
(MC-25) Unify the clauses with the join expression clauses. Example: allow the syntax dataset { … } equivalent to  [ dataset ] { … }. In this way a single syntax exists. Unify calc and attrcalc ( attrcalc  is a particular case of calc).

**Comment by capacma** [comment]
Currently we have 2 operators that have some clauses in common: 
1. join expression (RM page 50 line 1727) has the syntax: { [ join_clause ] } { body }
2. clause operators (RM page 166 line 5353) has the syntax: dataset [ different clauses ... ]
The idea is to choose only 1 operator.
**Proposal** 
The proposal is to have the following:
{ [ join_clause ] } { body }
dataset { body }
where body is the current body described under the join (with no changes).
Note concerning the calc and attrcalc operators:
In the above proposal, the syntax:
calc_clause := { role } compName = k
is replacing the calc operator. The attrcalc can be eliminated because it is a special case of calc.

**Comment by fewagener** [comment]
Do you mean to have a syntax like
{ [ join_dataset ]|dataset } { clause { , clause } * }
?
But then it would mean that you can use a join wherever you want. If this is idea, then it's fine with me.

**Comment by capacma** [comment]
In the above syntax, the join is always followed by a list of clauses e.g.:
 [ ds1 join ds2 ] { keep obs_value ; filter ref_area = "IT" }
In theory we could use the join without the clauses but then the measures and attributes will have a name that contains the dataset name, e.g.  [ ds1 join ds2 ] will have a measure ds1.ref_area. In the current description this special case is accepted in the clauses but not in all VTL expressions. Of course we may decide to extend it to all VTL expressions - fine with me.

**Comment by egreising** [comment]
I have a doubt (please @capacma @VincDV @bellomarini @dragan-ivanovic correct me if I am wrong): I have the idea that a clause was a special type of operator that could be "attached" to another operator to alter the content (e.g. keep columns, rename, etc) of the resulting dataset. (by the way I've noted that there is no "drop" clause in the RM except for the join...). For example, the paragraph in lines 3102 - 3104 in the UM makes me understand this.
Also the Use cases prepared by @vignola for the Ver. 1.0 had this example:
"The difference between age at the moment of the interview and the age of marriage is less than 14"

AGE_LT_Y14:= ds[rename SG23 as "CONDITION"]#CONDITION - ds[rename SURVEY_YEAR as "CONDITION"]#CONDITION) + ds[rename SG21 as "CONDITION"]#CONDITION < 14

where the clause "rename" is embedded in a calculation.

So, if my assumptions are correct, how will this proposed syntax change affect this usage?

**Comment by capacma** [comment]
According to the proposal, there are no changes affecting the usage. You can write:

AGE_LT_Y14 := 
  ( ds { rename SG23 to CONDITION } . CONDITION  
    - ds { rename SURVEY_YEAR to CONDITION } . CONDITION ) 
  + ds { rename SG21 to CONDITION } . CONDITION < 14

so the only changes are the different types of parentheses etc.

**Comment by bellomarini** [comment]
Agreed on this syntax during the meeting:

```
rename x to y
```
