### ISSUE TITLE
Review Semantic Specifiation & Constraint.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#250]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB-25|RM|168|168
***

### Issue Description
The semantics of keep states that:  The operator keep returns the input Dataset with only the Identifier and Measures Components specified as parameters.However, in the semantic specification is stated that: … (Identifier Components are not affected by the keep)…In line 5449 is also said that:  cmp cannot be a reference to an Identifier Component.

### Proposed Solution
According to the semantic and examples, the semantic specification should be reviewed and the constraint.

**Comment by fewagener** [comment]
In the constraint section is also stated that "cmp cannot be a reference to an Identifier Component". However, in the example keep affects the identifier components. My proposal would be to remove the constraint, however the problem is what to do with the duplicates in case they exist.

**Comment by linardian** [comment]
Refers to old version of documentation
