### ISSUE TITLE
String Concatenation operator

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#254]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MTNA-3|RM| |2114
***

### Issue Description
String Concatenation operator ||

### Proposed Solution
Use + as string concat operators like e.g. Stata, Python. Execution of String + Number will give "type mismatch".

**Comment by egreising** [comment]
Not an issue but a matter of personal preference. 
However, unless strong reasons to change from "+" to "||", I would keep "+" for backwards compatibility with VTL 1.0.

**Comment by linardian** [comment]
Refers to old version of documentation
