### ISSUE TITLE
Filters must be "boolean expressions".

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#256]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MTNA-6|RM| |5408
***

### Issue Description
Filters must be "boolean expressions".

### Proposed Solution
Treat all expressions as boolean, just as in Stata or the C programming language (https://www.le.ac.uk/users/rjm1/cotter/page_37.htm)

**Comment by dragan-ivanovic** [comment]
I do not agree with the proposed solution to implicitly convert any scalar to Boolean.  The implicit conversion in C are a source of many bugs and problems, and are generally avoided in post-80s era of programming languages.

If we require Boolean (as is the case now), then:
```
filter 2*x+3
```
is obviously wrong and the compiler raises a type error.  If we really wanted to succeed only when `2*x+3 ` is different than zero, we just need to write:
```
filter 2*x+3<>0
```
and it is completely clear what we mean.

Also:
```
filter x
```
works only if component `x` is Boolean.  If it isn't it raises an error. This leaves us on the safe side: what if the actual dataset has `x` as a date?  When is a date `true` or `false` is open to interpretation and specific needs of the developer.

**Comment by linardian** [comment]
Refers to an old version of documentation
