### ISSUE TITLE
Transcode operator definition_arguments.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#257]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
AG-5|RM|122-123|4073, 4108
***

### Issue Description
In the transcode operator definition there are only two arguments in the parenthesis but in the examples 3 arguments are used. Definition: transcode(ds.comp, [ds_map| mapping])   example: ds_2 := transcode( ds, ds_map, REF_AREA ).

### Proposed Solution
Change definition to:   transcode( ds, ds.comp, [ds_map| mapping] ).

**Comment by egreising** [comment]
It is exactly the same issue as #44. I assign to @stratosn for closing.
