### ISSUE TITLE
Hierarchy and Aggregate.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#258]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-26|RM|123 - 130, 139|hierarchy and aggregate
MC-45|RM|127-130, 139|hierarchy and aggregate
***

### Issue Description
(MC-26) Unify hierarchy and aggregate.
(MC-45) Conversions from  hierarchical ruleset to hierarchy dataset, from hierarchy dataset to hierarchical rulset.

### Proposed Solution
(MC-26) A single operator takes either a hierarchical dataset or a dataset containing (parent, child, …)
(MC-45) New conversion functions: hierarchical ruleset to hierarchy dataset from hierarchy dataset to hierarchical rulset.

**Comment by linardian** [comment]
Refers to old version of documentation
