### ISSUE TITLE
Parameter for calculation method.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#259]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-GOV-16|RM|124, 127|4112-4216
***

### Issue Description
Function aggregate has no parameter determining calculation method. There’s only sum aggregation in examples.

### Proposed Solution
Add parameter for calculation method.

**Comment by linardian** [comment]
Refers to old version of documentation
