### ISSUE TITLE
Harmonise the use of "," and ";"

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#260]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB2-8|RM|32,46,52|838, 1512, 1736
***

### Issue Description
It would make sense to harmonize the usage of “,” and “;” (i.e. symbols to split objects / lines). For example in case of a datapoint ruleset (see line 838) the symbol “;” is used to separate the individual rules. In case of a join expression (see line 1736) each clause of the join body is separated by the symbol “,” which is also the separator for methods applied in a get() function (see line 1512).

### Proposed Solution
Harmonise the use of , and ;

**Comment by fewagener** [comment]
It seems the comma "," is more widely used in VTL as a separator. So, I would change the semicolon ";" with a comma in datapoint ruleset

**Comment by vignola** [comment]
can we consider this issue similar to #338 ?
