### ISSUE TITLE
Datasets multimeasures  & monomeasures.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#262]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-64|RM|60, 70, 72, 85, 86, 87, 89, 104, 106, 107|2131, 2501, 2566, 3045, 3093, 3142, 3198, 3611, 3656, 3701

### Issue Description
Possible cases are: ds1 and ds2 scalars, ds1 and ds2 datasets with one or more measures in common or both mono measures but there is not the case of one multi measures and one mono measures.

### Proposed Solution
Add the case of one dataset multimeasures and one monomeasures or  change the constaints "or at least one of them has only a measure" with "or both of them have only one measure".

**Comment by linardian** [comment]
Refers to an old version of documentation
