### ISSUE TITLE
Boolean as scalar.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#264]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-70|RM|85, 86, 87, 89|3038, 3086, 3135, 3191
***
>

### Issue Description
Boolean as scalar-type is not correct.

### Proposed Solution
Replace it with "scalar"

**Comment by linardian** [comment]
Refers to an old version of documentation
