### ISSUE TITLE
Named parameters in VTL 1.0.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#265]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
BDI-26|RM|all|All
***

### Issue Description
Named parameters, which were present in VTL 1.0 seem to be not allowed anymore. 

### Proposed Solution
They should restored from VTL 1.0, also for back-compatibility.

**Comment by bellomarini** [comment]
Discussion open.

**Comment by linardian** [comment]
Refers to an old version of documentation
