### ISSUE TITLE
Uniform syntax description

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#266]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-16|RM|all|Description
***

### Issue Description
Choose a uniform syntax description (e.g. avoid "ds := ..." and description of the type of object in the syntax).Verify that the uniform description is applied everywhere.

### Proposed Solution
Partially done, To be done.

**Comment by linardian** [comment]
Refers to an old version of documentation
