### ISSUE TITLE
Composed operator name

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#268]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-7|RM|all|
***

### Issue Description
Could it be more simple to have only one way to define a composed operator name (for example with _ or using the first name un lower case and the others in the upper case)? E.g defineFunction and time_aggregate.

**Comment by vignola** [comment]
#336

**Comment by vignola** [comment]
#336
