### ISSUE TITLE
Change dimension with identifier

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#269]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-16|RM|all|
***

### Issue Description
The word dimension derives from SDMX.
 
### Proposed Solution
Change everywhere dimension with identifier

**Comment by capacma** [comment]
The term "identifier" is wrong (can be confused with "identifier" denoting syntactical elements)
The term "identifier component" could be used but it is of difficult understanding.
The term dimension is well understood by the users.
So the best solution would be that of using the following terms: dimension, measure, attribute.

**Comment by linardian** [comment]
Refers to an old version of documentation
