### ISSUE TITLE
New operator: get_def_value_list ( dataset, dimension ) . Returns the list of values specified in the definition of the dataset.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#274]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-48|RM|new|get list of dimension values
MC-49|RM|new|get list of dimension values
***

### Issue Description
(MC-48) New operator: get_def_value_list ( dataset, dimension ) . Returns the list of values specified in the definition of the dataset.
(MC-49) New operator: get_def_value_list ( dataset, dimension ). Returns the list of values specified in the definition of the dataset.

### Proposed Solution
(MC-48) New operator: get_def_value_list ( dataset, dimension ) Returns the list of values specified in the definition of the dataset.
(MC-49) New operator: get_def_value_list ( dataset, dimension ).Returns the list of values specified in the definition of the dataset.

**Comment by capacma** [comment]
**Proposed Solution**
New operator: get_def_values( dataset, dimension ). Returns the list of values (of the given dimension) specified in the definition of the dataset.
New operator: get_all_values ( dataset, dimension ). Returns the list of values (of the given dimension)contained in the data points of the dataset.

**Comment by linardian** [comment]
It seems more a service for a registry than a VTL operator. For this reason this issue is closed
