### ISSUE TITLE
Simplify Operator.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#279]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-45|RM|-| from 1077
***

### Issue Description
The sentence can confuse readers when it comes to the "space of event" or a code that represent an event.

### Proposed Solution
Make the explanation of the operator more simple than possible.

**Comment by linardian** [comment]
Refers to an old version of documentation
