### ISSUE TITLE
Flexible way to recognize a date from a string.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#280]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-66|RM|-|2388
***

### Issue Description
Is not possible to define a flexible way to recognize a date from a string? For example italian string for date can be DD-MM-YYYY and it is not included as possible format.

### Proposed Solution
Make the format more flexible using a flexible combination of DD and MM (or MMM) and YYYY (or YY) etc…or eliminate directly the format nad let the owner to the compiler.

**Comment by egreising** [comment]
The line reference (2388) is misleading, probably refers to 2353 (table of allowed patterns for date formatting in _date_from_string_ operator).
The overall description of the operator should be revised. It seems to be confusing the concept of "periodicity" or "frequency" (a Time-related concept, normally represented with the data type "Observational Time Period" in SDMX) with "date".
The formats in the table in line 2353 are Time formats not representing dates.

**Comment by egreising** [comment]
This issue is linked to #245

**Comment by linardian** [comment]
Refers to old version of documentation
