### ISSUE TITLE
Details for "slicing" operations.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#285]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-1|UM|45|
***

### Issue Description
There are no details, neither here nor in Part 2, on how to use "slicing" operations (e.g. integer[a:b] or string[a]). There are also no details whatsoever on lists, sets, and collections. In fact, in Part 2, there are no sets (apart from datasets) or collections - while lists are vaguely referred to at some occasions, under some functions.

### Proposed Solution
Add details.

**Comment by linardian** [comment]
Refers to old version of documentation
