### ISSUE TITLE
Syntax - "join" operation

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#288]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-4|UM|54|1883
***

### Issue Description
The ç has different syntax in Part 2 (e.g. " [outer ds1, ds2] ").

### Proposed Solution
Follow Part 2.

**Comment by capacma** [comment]
The "join" operation has different syntax in Part 2 (e.g. " [outer ds1, ds2] ").

**Comment by linardian** [comment]
Refers to old version of documentation
