### ISSUE TITLE
Part 2 (use isnull())

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#290]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-6|UM|65,66 &elsewhere|
***

### Issue Description
There is no "is null" or "is not null" operator in Part 2; it uses the "isnull()" function only.

### Proposed Solution
Follow Part 2 (use isnull())

**Comment by linardian** [comment]
Refers to old version of documentation
