### ISSUE TITLE
Syntax_Spaces

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#291]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-7|RM|24-30|436, 510, 514
***

### Issue Description
Definition syntaxes inconsistently use or do not use space separators: e.g. "defineValueDomain" at line 436, while "define ValueDomain" at line 510 and 514; and similar differences in case of ValueDomainSubsets, and Structures, and Datasets (mainly: examples differ from the main Syntax descriptions). 

### Proposed Solution
No spaces
@capacma the standard form should be:
**define** space objectType
where objectType can be dataset, datapoint ruleset etc.
proposal for value domain (coherent with other existing types of objects):
define value domain

**Comment by vignola** [comment]
this issue is similar to #336 maybe we can merge in one

**Comment by bellomarini** [comment]
I agree with the proposed solution.

**Comment by linardian** [comment]
Refers to an old version of documentation
