### ISSUE TITLE
"Anytime a …" -> The sentence is grammatically problematic, let alone hardly comprehensible.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#292]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-8|RM|25|499
***

### Issue Description
"Anytime a …" -> The sentence is grammatically problematic, let alone hardly comprehensible.

### Proposed Solution
Revise

**Comment by bellomarini** [comment]
I suggest to rephrase as follows:

"All the possible combinations that are allowed in multi-dimensional ValueDomain are specified in the definition of the ValueDomain itself."

**Comment by linardian** [comment]
Refers to an old version of documentation
