### ISSUE TITLE
"persistent Dataset artefact" (defined by this "defineDataset" operator")

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#294]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-10|RM|29|
***

### Issue Description
I could not find any function in the Manual that would use the "persistent Dataset artefact" (defined by this "defineDataset" operator") either for validation or for any other purpose.

### Proposed Solution
Add dataset structure validation function.

**Comment by bellomarini** [comment]
It is just matter of explanation, since the Dataset defined by this operator is exactly like those used by the others. The *datasetId* can then appear in any part of the syntax where a Dataset can appear.

**Comment by linardian** [comment]
Refers to an old version of documentation
