### ISSUE TITLE
Line 985 vs. line 1001_Consistency in format.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#295]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-11|RM|34|985,1001
***

### Issue Description
Line 985 vs. line 1001 -> capitalization is not consistent; nor are they in the examples on the following pages.

### Proposed Solution
Make consistent.

**Comment by linardian** [comment]
Refers to an old version of documentation
