### ISSUE TITLE
Add  "msr" under the "Parameters" section.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#299]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-15|RM|51|1743, 1744
***

### Issue Description
What is "msr"? I suppose a Measure Component, but it is not included under the "Parameters" section.

### Proposed Solution
Add it

**Comment by linardian** [comment]
Refers to old version of documentation
