### ISSUE TITLE
Syntax - parameter "alias"

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#300]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-16|RM|51|1755
***

### Issue Description
The parameter "alias" is not in the syntax or anywhere else in the description of the join expression. Besides, the sentence is incomplete.

### Proposed Solution
Revise

**Comment by capacma** [comment]
This issue is raised also in #170, I propose to close it and work on #170.
