### ISSUE TITLE
This sentence lacks basic punctuation and/or proper conjunctions.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#301]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-17|RM|53|1852
***

### Issue Description
This sentence lacks basic punctuation and/or proper conjunctions.

### Proposed Solution
It should be revised to be comprehensible, e.g. divided into 3 separate sentences ("… Dataset. When … is null. Compare ...").

**Comment by capacma** [comment]
Solution:
2) outer join returns data points that exist in at least one Dataset. When a data point does not exist in the other Dataset, the value of its measures and components is null. Compare with the following example:
