### ISSUE TITLE
Examples 2 and 3 have the exact same input, but different outputs (true vs. false). 

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#309]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-25|RM|102-103|
***

### Issue Description
Examples 2 and 3 have the exact same input, but different outputs (true vs. false). 

### Proposed Solution
I would say example 3 is wrong: there is one and only one Data Point (the second row) that satisfies the given conditions.

**Comment by vignola** [comment]
yes the example page 103 mut be corrected, for example with the folliwing example
ds_2 := unique (ds_1.VALUE_2000>100 AND ds_1.VALUE_2001>80) that returns two data points respecting the input so not only one (result =FALSE)
