### ISSUE TITLE
Typo error in Reference Manual

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#31]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-CSO-22|RM|24|445
***
Issue|Proposed Solution
-----|------
Type “scalar” suggests that the parameter accepts operands of any scalar type ( integer, float, string etc.).|Should be “scalar-type”

**Comment by amattioc** [comment]
outdated
