### ISSUE TITLE
"before performing"

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#311]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-27|RM|121|4049
***

### Proposed Solution
"before performing". But, besides that, I think what really happens is in reverse order as compared to what is suggested in the description: actually, first the filtering is done, and only then the respective components are removed.
@capacma
Replace:
This operator removes identifiers components of the Dataset performing before a filter over the components values specified in the subscript. This avoids inconsistency on the returned Dataset
with
This operator filters ds using the specified identifier values and then removes the specified identifier components. The returned Dataset does not contains duplicates. Example: suppose that ds_1 has identifier components (time, ref_area, partner) then ds_1 [ ref_area = EU25 ] is equivalent to ds_1 { filter ref_area = EU25 , keep time, partner }

**Comment by linardian** [comment]
Refers to an old version of documentation
