### ISSUE TITLE
Aggregate() function & other elements in the hierarchical ruleset. 

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#312]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-28|RM|124|
***

### Issue Description
How would this aggregate() function interpret inequality rules (e.g. "A > B") and other elements in the hierarchical ruleset that are related to validation (e.g. errorcodes)? It would simply ignore them?

### Proposed Solution
Explain, add in example

**Comment by linardian** [comment]
Refers to an old version of documentation
