### ISSUE TITLE
Syntax & hierarchical rulesets.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#313]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-29|RM|124-126, 34-39|
***

### Issue Description
The examples of the hierarchical rulesets have different syntax (first line) compared to what is specified under the "hierarchical rulesets" description (pp. 34-39).

### Proposed Solution
Make consistent.

**Comment by linardian** [comment]
Refers to an old version of documentation
