### ISSUE TITLE
It is not specified which of the two summation will be returned in the results dataset, and why.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#314]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-30|RM|126|4209-4210
***

### Issue Description
It is not specified which of the two summation will be returned in the results dataset, and why.

### Proposed Solution
Specify

**Comment by linardian** [comment]
Refers to an old version of documentation
