### ISSUE TITLE
This syntax is completely different from the syntax given on page 130, and also from the other example.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#316]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-32|RM|132|4356
***

### Issue Description
This syntax is completely different from the syntax given on page 130, and also from the other example.

### Proposed Solution
Make consistent.

**Comment by linardian** [comment]
Refers to old version of documentation
