### ISSUE TITLE
"GEO" -> "NACE" and "mult_rule" -> "mult_measure" (if I understand correctly).

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#320]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-36|RM|147|4767
***

### Issue Description
"GEO" -> "NACE" and "mult_rule" -> "mult_measure" (if I understand correctly).

### Proposed Solution
Revise

**Comment by linardian** [comment]
Refers to an old version of documentation
