### ISSUE TITLE
What is "list<components-ref>" (lines 5037, 5046)? Moreover, what exactly is "list<valueDomain-ref>" (line 5047)?

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#322]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-38|RM|155, 156|5037, 5046, 5407
***

### Issue Description
What is "list<components-ref>" (lines 5037, 5046)? Moreover, what exactly is "list<valueDomain-ref>" (line 5047)?

### Proposed Solution
There should be an actual, tangible example and/or adequate explanation.

**Comment by linardian** [comment]
Refers to old version of documentation
