### ISSUE TITLE
fill_time_series function

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#323]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-39|RM|157|
***

### Issue Description
What value types does this fill_time_series function accept? The example implies that it is not only dates (since the TIME column's values are simple years). So perhaps both dates and integers? Or does it automatically recognize and interpret date format in string values (and so these are strings in this TIME column)?

### Proposed Solution
Explain

**Comment by capacma** [comment]
Correct the example:
ds_bop
TIME 	REF_AREA 	PARTNER 	FLOW	OBS_VALUE 
2010	IT	US	NET	10 
2012	IT	US	NET	50
2010	DE	US	NET	25
2013	DE	US	NET	75

ds_fill_ts := fill_time_series ( ds_bop, "A", time )
ds_fill_ts
TIME 	REF_AREA 	PARTNER 	FLOW	OBS_VALUE 
2010	IT	US	NET	10 
2011	IT	US	NET	null
2012	IT	US	NET	50
2010	DE	US	NET	25
2011	DE	US	NET	null
2012	DE	US	NET	null
2012	DE	US	NET	75

Note: 1 data point is inserted for the series (IT, US, NET) and 2 data points are inserted for the series (DE, US, NET).

**Comment by capacma** [comment]
Correct the reference manual:

Constraints
The Dataset ds must have the specified the Identifier Component timePeriodName or the default "time".

Correction:
Change time to time_period

**Comment by linardian** [comment]
Refers to old version of documentation
