### ISSUE TITLE
"ts_2 := timeshift( ts_1, Q, 3 )"

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#324]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-40|RM|161|5228
***

### Issue Description
"ts_2 := timeshift( ts_1, Q, 3 )"

### Proposed Solution
"ts_2 := timeshift( ts_1, Q, 4 )"

**Comment by linardian** [comment]
Refers to an old version of documentation.
