### ISSUE TITLE
errorLevel & definition, one approach and apply it consistently.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#330]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-46|RM|-|855, 1022, 4930
***

### Issue Description
errorLevel is spelled differently throughout the document, sometimes with capitalised L and sometimes without. Moreover, in the three lines mentioned, it has different types (once it is defined as an integer-literal, once as an integer-constant and once as simply an integer).

### Proposed Solution
Just choose one approach and apply it consistently

**Comment by linardian** [comment]
Refers to an old version of documentation
