### ISSUE TITLE
Description of lists and list functions/operations.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#333]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-49|UM|-|
ESTAT-49|RM|-|
***

### Issue Description
A thorough description of lists and list functions/operations would be essential.

### Proposed Solution
E.g. a list could be defined as list_1 := ("A2", "B34", "G7"). Basic operations should include e.g. sorting, returning length, selecting/removing/adding elements (select/remove either by name or by index, add either by appending to the end or inserting to specified index), deriving a set (only unique elements), etc.

**Comment by linardian** [comment]
Refers to an old version of documentation
