### ISSUE TITLE
Add more examples, illustrating various possibilities/elements/clauses under each function.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#337]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-53|UM|-|
ESTAT-53|RM|-|
***

### Issue Description
I think there should be much more examples, illustrating various possibilities/elements/clauses under each function, and they should include more thorough and clear description of what is happening exactly, how the variables/datasets change, etc.

### Proposed Solution
Add

**Comment by linardian** [comment]
Notes on obsolete version of documentation
