### ISSUE TITLE
Clarify the use of semicolons.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#338]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-54|UM|-|
ESTAT-54|RM|-|
***

### Issue Description
Semicolons are inconsistently used or not used for line-endings within the code throughout the Manual, and there is no explicit description about how exactly they should be used and what purpose they serve (if any).

### Proposed Solution
@dragan-ivanovic: Clarify and keep as is.
~~Clarify (or simply remove).~~
@capacma: the statement-level separator should be well defined. the newline should not be used to separate two statements (see comment below for explanation), therefore the best option is to use the semicolon ";" because it cannot be confused with the list separator (",")

**Comment by dragan-ivanovic** [comment]
In all cases semicolons are optional. The language syntax allows them for better visibility and to catch syntax errors such as unclosed parentheses or incomplete expressions. That is common in langauges where line breaks are not significant. Example:
```
[d1,d2] {
  measure z := 3*((d1.x - d2.x)/(d1.x-d2.x-)
  filter  z> 0
}
```
Here, the parser will complain that `filter` is not a valid infix operator.  If we put the semicolon at the end of the previous line, the error will be raised at the semicolon saying that an infix operator or closed parenthesis is expected.

**Comment by linardian** [comment]
Refers to old version of documentation
