### ISSUE TITLE
Typo in example operator round/ceil/floor

### ISSUE THREAD

**Issue by fewagener** [sdmx-twg/vtl#344]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
-|RM|74|2643
***
### Issue Description
The example 4) of operator round/ceil/floor has a typo: the value 7 of the second observation of ds_1 should be 8
### Proposed Solution
Correct the typo

**Comment by morrme** [comment]
I can't seem to find the documents mentioned in these issues to help fix them.

**Comment by amattioc** [comment]
fixed in https://github.com/sdmx-twg/vtl/commit/d301d6dccadb038d1bb619a361a4c798f7fecdef
