### ISSUE TITLE
Missing Tokens

### ISSUE THREAD

**Issue by DGSbird** [sdmx-twg/vtl#345]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
BIRD-1|EBNF||
***

### Issue Description
The tokens **DIFF** (Vtl.g4, line 277), **PRECEDING** (Vtl.g4, line 474), **FOLLOWING** (Vtl.g4, line 475), **SYMDIFF** (Vtl.g4, line 693), **NUMBER** (Vtl.g4, line 735) are not defined in VtlTokens.g4 although they are used in the parser rules (i.e. Vtl.g4).

### Proposed Solution
Add tokens to VtlTokens.g4.

**Comment by linardian** [comment]
Notes on obsolete version of documentation
