### ISSUE TITLE
Anonymous & define

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#35]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV-3|UM/RM|51|1748
LV-4|UM/RM|53|1840
***
The anonymous function is not mentioned anywhere in the reference manual
Should we include it  in the reference manual with examples?

**Comment by bellomarini** [comment]
Or move it to the "technical manual"?

**Comment by linardian** [comment]
Notes regarding an old version of the documentation
