### ISSUE TITLE
Typographic conventions

### ISSUE THREAD

**Issue by capacma** [sdmx-twg/vtl#352]
### Issue Description
Harmonisation of the syntax

**Comment by capacma** [comment]
Document discussed in Luxembourg 26-27-28 April (Luigi)
[Typographic conventions_20160502.xlsx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/975705/Typographic.conventions_20160502.xlsx)

**Comment by linardian** [comment]
Notes on obsolete version of documentation
