### ISSUE TITLE
Operator: exists_in

### ISSUE THREAD

**Issue by capacma** [sdmx-twg/vtl#359]
### Issue Description
New definition of exists_in that will replace exists_in, exists_in_all, not_exists_in, not_exists_in_all
### Proposed Solution
**exists_in** is a boolean operator. The syntax is functional:
**exists_in** ( ds1, ds2, retain ) 
string retain = **all** | **true** | **false**
**all** return all data points (default value)
**true** returns the data points in ds2
**false** returns the data points not in ds2

Constraint: ds1 has all the identifiers of ds2 or ds1 has all the identifiers of ds2

NB: retain could be harmonised with similar option of the check operator.

exists_in_all, not_exists_in, not_exists_in_all will be removed from the RM.

To be investigated after July unless we can do it before: how to treat foreign keys stored in measures (instead of identifiers). Possible solutions to be analysed:
exists_in ( ds1, ds2, false, [ id_1, id_2 ] , [ id_1, id_2 ] )
or:
exists_in ( ds1 [ rename id_1 to id_2], ds2, false, [ id_1, id_2 ] )
ds1#student in ( ds2#student ) 
(ds1[keep m1, m2 ] ) in  (ds2[keep m1, m2 ]  )
Use the join
X := ds1[keep m1, m2 ; rename … ] ;

**Comment by linardian** [comment]
Notes on obsolete version of documentation
