### ISSUE TITLE
VTL programs and modules

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#36]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
BDI-17|UM/RM|56|All
***
There is no reference to the concepts of modules or programs, defined in the user manual. The specification is largely incomplete for what concerns the packaging of the programs, the import of libraries. In effects, it is not clear how to write a VTL program.
Explain how to specify them.

### Proposed Solution

Define in the reference manual the definition of: 
- main programs
- modules (user-defined and virtual).

Follow the outline of the type system as proposed in issue #283.

**Comment by bellomarini** [comment]
A possible discussion about modules and programs should appear in the Appendix or in a third programmer manual, since it appears too technical for a business user, who is more likely to be interested only in the validation rules.

**Comment by dragan-ivanovic** [comment]
The description of the type system, together with the module system, is explained in file `type-sys.pdf` attached to issue #283.

**Comment by linardian** [comment]
Discussion about modules and programs will be taken in the VTL physical group meeting in May. Probably this topic will be inserted in tehe technical manual to be part of VTL 2.1 version
