### ISSUE TITLE
List of operators and parameters that could be published after July

### ISSUE THREAD

**Issue by capacma** [sdmx-twg/vtl#361]
### Issue Description
List of operators and parameters that could be published after July

[List of operators that could be published after July.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1111215/List.of.operators.that.could.be.published.after.July.docx)

**Comment by egreising** [comment]
[List.of.operators.that.could.be.published.after.July-EG.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1127742/List.of.operators.that.could.be.published.after.July-EG.docx)

**Comment by capacma** [comment]
Comments by Vincenzo
[List.of.operators.that.could.be.published.after.July_vdv.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1127815/List.of.operators.that.could.be.published.after.July_vdv.docx)

**Comment by capacma** [comment]
Conclusions on the proposals discussed in the teleconference on 6 July 2017.
[List.of.operators.that.could.be.published.after.July_vdv.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1133057/List.of.operators.that.could.be.published.after.July_vdv.docx)

**Comment by capacma** [comment]
Document updated after the teleconference held on 20 July.
[Comments operators Thursday 20 July MC.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1291589/Comments.operators.Thursday.20.July.MC.docx)

**Comment by linardian** [comment]
Notes on obsolete version of documentation
