### ISSUE TITLE
Define a consistent behaviour of the set operators

### ISSUE THREAD

**Issue by capacma** [sdmx-twg/vtl#362]
### Issue Description
The Set operators must be defined in a consistent way.
### Proposed Solution
1. It is proposed that all set operators (union, setdiff, symdiff) work on the identifiers only to compare the data points of the operand datasets. They do not look at the values of measures and attributes.
2. As an alternative to 1., the set operators (union, setdiff, symdiff) should have an option that can be chosen to work either on identifiers only or on all components.
3. In the absence of the dedup function parameter, the operator intersect raises a run-time error when the two operand datasets contain data points with the same identifier values (or all component values, depending on the definition chosen in 1. and 2.). This behaviour is not satisfactory. It is proposed to define the intersect operator in an acceptable way or to postpone the publication to a future release.

**Comment by linardian** [comment]
Refers to an olda version of documentation
