### ISSUE TITLE
DML operators - main changes in VTL 2.0 with respect to 1.1

### ISSUE THREAD

**Issue by capacma** [sdmx-twg/vtl#364]
### Issue Description
Describe the main changes between 2.0 and 1.1
### Proposed Solution
DML operators - main changes in VTL 2.0 wrt 1.1

**Comment by capacma** [comment]
[VTL 2.0 changes in the DML syntax wrt 1.1 update 2017.09.07.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1283965/VTL.2.0.changes.in.the.DML.syntax.wrt.1.1.update.2017.09.07.docx)

**Comment by linardian** [comment]
Paragraph is present in the 2.0 version
