### ISSUE TITLE
Teleconferences

### ISSUE THREAD

**Issue by capacma** [sdmx-twg/vtl#365]
### Issue Description
Minutes of teleconferences

**Comment by capacma** [comment]
Teleconference 07 September 2017
[VTL Teleconference 07 September 2017.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1285000/VTL.Teleconference.07.September.2017.docx)

**Comment by capacma** [comment]
Teleconference 20 September 2017

Continuation of the discussion points of the last teleconference:
The join doc updated by Luigi #363
 Clauses outside the join, document by Luigi #363
 fold, unfold will be renamed to unpivot, pivot
 subscript is renamed to subspace 
 datasets with 0 identifiers : can be produced by a subscript or by an aggregate function
 Example:
  ds has measures m1, m2
  sum ( ds )
  put ( ( sum ( ds ) )  [ calc refarea = IT ] , ds_persistent )

In the pipe:
·	Get (document by Luigi #363)
·	Time series functions (document by Maurizio #366)
·	Analytic functions (sql-like syntax vs functional syntax)
·	Syntax of define dataset, define data structure, define valuedomain, define valuedomainsubset
·	Syntax to declare viral attributes and associate a propagation function
·	User manual
·	Rules for identifiers and object names

**Comment by linardian** [comment]
Old and currently useless notes.
