### ISSUE TITLE
Set operators

### ISSUE THREAD

**Issue by capacma** [sdmx-twg/vtl#367]
Proposal by Luigi
[set_operators_20171011.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1375522/set_operators_20171011.docx)

- error for duplicates in union
- error for intersection only in case of ambiguity (same id, different measures)
- no error for symdiff
- error for setdiff

**Comment by linardian** [comment]
Notes on obsolete version of documentation
