### ISSUE TITLE
check

### ISSUE THREAD

**Issue by capacma** [sdmx-twg/vtl#369]
check operator

The proposal is harmonised in the sense that the output has always the same structure and the parameters are consistent. Of course the single check has additional parameters that in the other types of check are specified in each rule of the ruleset.

[Proposal to harmonise the different types of check.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1558804/Proposal.to.harmonise.the.different.types.of.check.docx)

**Comment by capacma** [comment]
Corrected:
[Proposal to harmonise the different types of check 2.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1558806/Proposal.to.harmonise.the.different.types.of.check.2.docx)

**Comment by linardian** [comment]
Refers to an old version of documentation.
