### ISSUE TITLE
User and reference manual latest versions

### ISSUE THREAD

**Issue by capacma** [sdmx-twg/vtl#373]
The manuals sent to the SDMX Secretariat are here:
[VTL-2.0 - Reference-Manual draft.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1766393/VTL-2.0.-.Reference-Manual.draft.docx)
[VTL-2.0 - User-Manual draft.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1766396/VTL-2.0.-.User-Manual.draft.docx)

**Comment by linardian** [comment]
New version ongoing
