### ISSUE TITLE
Repository status and last version?

### ISSUE THREAD

**Issue by hadrienk** [sdmx-twg/vtl#380]
What is the status of this repository? I just got hold of a new version of the specification (stil version 2.0) but cannot see the changes in this repository.

**Comment by stefanopam** [comment]
> What is the status of this repository? I just got hold of a new version of the specification (stil version 2.0) but cannot see the changes in this repository.

You can find the announcement together with the new version at https://sdmx.org/?sdmx_news=new-version-of-the-vtl-2-0-extended-backus-naur-form-july-2020.
We will update the Git repository asap

**Comment by amattioc** [comment]
Hi @hadrienk , we started the development of the 2.1 version of VTL. The repository is being cleaned up of all old issues and the documentation is being revamped.
