### ISSUE TITLE
Error in the grammar for when then

### ISSUE THREAD

**Issue by antonio-olleros** [sdmx-twg/vtl#387]
### Issue Description
The following expression inside a datapoint ruleset yields semantic error:
`when SecurityType not in securities_with_maturity then isnull(MaturityDate)`

While this one works:
`when SecurityType  in securities_with_maturity then isnull(MaturityDate)`

### Proposed Solution
Fix the grammar

**Comment by vpinna80** [comment]
"not_in" is the correct expression, with an undescore instead of space.

**Comment by antonio-olleros** [comment]
You are completely right... Sorry, I'll close the issue

**Comment by antonio-olleros** [comment]
There is no error, it was my bad
