### ISSUE TITLE
Harmonization of Hierarchy operator, Aggregate operator, Hierarchical Ruleset

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#39]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
BDI-27|RM|34|34 seg., 39, seg.
MC-26|RM|123 - 130, 139 -|hierarchy and aggregate
MC-45|RM|127-130, 139|hierarchy and aggregate
***

### Issue Description
(BDI-27) The Hierarchical Ruleset and the Hierarchy operator are very largely overlapped. In particular, they do almost completely the same job  as for the aggregation and in a very similar way. The main difference is that in the Hierarchical Ruleset the Code Item Relations are written in-line, while the Hierarchy operator considers them as externally stored artefact. This difference would disappear if every Operator is allowed to read external artefacts or write them in-line, as suggested in another observation   

(MC-26) Unify hierarchy and aggregate

(MC-45) Conversions from  hierarchical ruleset to hierarchy dataset, from hierarchy dataset to hierarchical rulset

### Proposed Solution
(MC-26) a single operator takes either a hierarchical dataset or a dataset containing (parent, child, …)

(MC-45) New conversion functions: hierarchical ruleset to hierarchy dataset from hierarchy dataset to hierarchical rulset

(BDI-27) Integrate the Hierarchical Ruleset and the Hierarchy Operator, allow the Hierarchical Ruleset to access externally stored artefacts and the Hierarchy Operator to write the artefacts in-line

**Comment by bellomarini** [comment]
the **aggregate** operator should apply:

* internally defined rulesets (with *define rulesets*)
* in-line defined rulesets (within the aggregate itself)
* ruleset extracted with a **GET** operator from the IM.

With the assumptions above, hierarchy and aggregate could me collapsed and we may keep aggregate only.
