### ISSUE TITLE
Random function

### ISSUE THREAD

**Issue by NicoLaval** [sdmx-twg/vtl#393]
See [here](https://github.com/VTL-Community/VTL-Community/issues/20) the start of the exchanges.

**Comment by vpinna80** [comment]
@romaintailhurat the random function is a pseudorandom sequence generator (i.e. not suitable for cryptography) and the seed is the initialization parameter of this pseudorandom function. The other parameter is the selector of the item in the generated sequence.

So for example random(10, 6) says: pass 10 as the initialization argument to the pseudorandom function, let it generate 6 numbers, and take the last.

If you look at the [Random](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html) class, the seed is what's passed to the constructor, and the index is how many times nextDouble() is called before returning a result.

@NicoLaval I agree that both parameters should be mandatory

**Comment by romaintailhurat** [comment]
Yes, i know how a seed works, my misunderstanding was on what was proposed by you and Angelo, so now it's clear. 😄 

And once again, i think that we should support both numbers and strings as seeds.

**Comment by linardian** [comment]
The current syntax of random operator has been approved. It will be part of VTL 2.1 versione
