### ISSUE TITLE
Replace - Regular expression

### ISSUE THREAD

**Issue by NicoLaval** [sdmx-twg/vtl#397]
### Issue Description
Quoting the Reference Manual: 
- `replace`:
(line 2723) `pattern1 the pattern to be replaced`

- `match_characters`:
(line 4104) `pattern: the regular expression`

For `replace` function, the second param, `pattern1` is a string.

**Can it be a regular expression?**

**I would say yes**

### Proposed Solution

Explicitly enable regex param for `replace`:
update line 2723: `pattern1 the pattern (regular expression) to be replaced`

**Comment by vpinna80** [comment]
Agree, also already implemented this way

**Comment by linardian** [comment]
Agreed. Current VTL  2.1 version document updated.
