### ISSUE TITLE
VTL module

### ISSUE THREAD

**Issue by romaintailhurat** [sdmx-twg/vtl#399]
There is an ongoing discussion on the topic of using modules or other constructs in order to organise VTL code.

@antonio-olleros said that its tool is already implementing a form of modules using the existing standard.

I also mentionned that it would be very interesting to have of solution at the standard level (not only in some implementations).

**Comment by antonio-olleros** [comment]
Hi all, I'm happy to present how we are dealing with the modules. I think it is a very natural solution that works well and actually requires no real change in VTL

**Comment by romaintailhurat** [comment]
Thank you @antonio-olleros. A presentation at the Salamanca meeting would be great.

**Comment by linardian** [comment]
Dear @romaintailhurat, as agreed, we will have a specific session on this during next meeting in Salamanca. See you there !
