### ISSUE TITLE
Add ‘sdmx’ Topic: Boost Discoverability for SDMX Repositories

### ISSUE THREAD

**Issue by hoehrmann** [sdmx-twg/vtl#400]
**Dear repository owners,** 🌟

As your repository is related to **SDMX** (Statistical Data and Metadata Exchange), please consider adding the **sdmx** topic to it. This will help other developers discover and engage with your project more easily.

To associate your repository with the **sdmx** topic, visit your repo's landing page and select **'manage topics'**. Let's make SDMX-related projects more visible and accessible! 🚀

Thank you for contributing to the community! 🙌

For detailed instructions on how to add topics to your repository, refer to the [GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics).

Happy coding! 🌐👩‍💻👨‍💻

**Comment by linardian** [comment]
Hello Bjorn. Actually VTL is under the "SDMX umbrella" just to ensure better governance and guarantee the smooth evolution of the language; since is "standalone" standard, being used also outside SDMX implementations, we would like not to follow your suggestion. Anyway, happy to discuss this topic whenever you like.

**Comment by hoehrmann** [comment]
@linardian The main effect adding the topic would have is that the repository would appear in this list https://github.com/topics/sdmx Note that you can add multiple topics, in which case it would appear in multiple lists that link topics together. Right now there are no topics at all for the repository, and the language box says it is about the Velocity Template Language, while the first word in the README text is literally »SDMX«. But it was just a suggestion, feel free to close the issue.

**Comment by linardian** [comment]
Thank you very much Bjorn for your suggestion. At the moment I am not allowed to add topics to VTL repo (I do not know why, perhaps @stratosn can help me in this).

**Comment by stratosn** [comment]
Hi @linardian, can you check if you are allowed to access the topics now?
I not, I will increase your access rights further.

**Comment by linardian** [comment]
Tahnk you so much Stratos !!! Now some topics have been added. thank you again Bjorn for the very useful suggestion!!!
