### ISSUE TITLE
Join docs

### ISSUE THREAD

**Issue by amattioc** [sdmx-twg/vtl#418]
1. Review current documentation and examples
2. Translate current docs and examples
3. Add new examples if needed

**Comment by javihern98** [comment]
Review this example accordingly (DS_2 should be added on VTL expression):
![image](https://github.com/user-attachments/assets/052d5cd8-1e82-4e07-af65-d568a97efcc2)

**Comment by javihern98** [comment]
Review Syntax and grammar files:

{ , ds { as alias } }* --> { , ds { as alias } }+ (to indicate that more than one must be present, to make a total minimum of two datasets, in accordance to the Syntax guidelines and to be reproduced in the ANTLR Grammar files.
