### ISSUE TITLE
Typo on example for 'define datapoint ruleset'

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#43]
reporter issue reference|document (UM/RM)|page|line
:--|:--|--:|--:
AG-4|RM|33|947
***

### Issue Description
The example for 'define datapoint ruleset' lacks the `end datapoint ruleset` line.

### Proposed Solution
Add `end datapoint ruleset` after the closing parenthesis on line 947.
Thus, the example should become:
```
define datapoint ruleset ruleset_1 (FLOW as x, OBS_STATUS as y) (
  flow_dr : when x = "CREDIT" or x = "AVERAGE" then y <> "C" errorcode ( -XXXXX )
)
end datapoint ruleset
```

**Comment by capacma** [comment]
Solution:
define datapoint ruleset ruleset_1 (FLOW as x, OBS_STATUS as y)
  flow_dr : when x = "CREDIT" or x = "AVERAGE" then y <> "C" errorcode ( -XXXXX )
end datapoint ruleset
