### ISSUE TITLE
Parameters of 'transcode' operator

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#44]
reporter issue reference|document (UM/RM)|page|line
:--|:--|--:|--:
AG-5|RM|122-123|4073, 4108
***

### Issue Description
In the `transcode` operator definition there are only two arguments in the parenthesis but in the examples 3 arguments are used.
definition:
```
transcode(ds.comp, [ds_map| mapping])
```
example:
```
ds_2 := transcode( ds, ds_map, REF_AREA )
```

### Proposed Solution
Change definition to:
```
transcode( ds, ds.comp, [ds_map| mapping] )
```

**Comment by vignola** [comment]
This is the same issue than #257
