### ISSUE TITLE
Zero Dimensions or Measures

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#46]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-22|UM|20|Allow dataset with 0 dimensions
MC-40|UM|20|0 dimensions
MC-41|UM|20|0 measures
***

### Issue Description
(MC-22, MC-40) Allow datasets with 0 dimensions. 
Rationale: allow the aggregate functions to return a dataset in the case "sum ( ds )". Also, this definition allow to define a uniform treatment for operands that can be scalar or dataset
(MC-41) Allow dataset with 0 measures ?

### Proposed Solution
(MC-22, MC-40) Allow dataset with 0 dimensions
(MC-41) Allow dataset with 0 measures ?

**Comment by capacma** [comment]
**Allowing datasets with 0 dimensions:**
In VTL a dataset is a mathematical function. A dataset with 0 dimensions can be seen as a constant function that always returns the same result. Allowing datasets with 0 dimensions fosters completeness and uniformity (between datasets and scalars). In fact, a scalar can be seen as a dataset with 0 dimensions and 1 measure (with a standard name, we have proposed "computed"). For example the scalar "1" is a dataset with 0 dimensions and 1 measure "computed" whose value is 1. Of course VTL requires that a dataset has at least a measure or attribute.
**Allowing datasets with 0 measures and attributes:**
In VTL a dataset is a mathematical function. A dataset with 0 measures and attributes corresponds to a mathematical function that does not provide any result, or whose result is undefined, therefore this should be defined in the UM. By accepting 0 measures and attributes (in addition to 0 dimension) VTL requires a dataset to have at least a dimension, measure or attribute. Note that, if we chose to forbid 0 measure and attributes then one can create a dataset with the desired dimensions and a dummy measure that contains any value (e.g. NULL) therefore allowing a dataset with 0 measures and attributes does not really increase the usability of the language.

**Comment by bellomarini** [comment]
We agree in general about allowing datasets with *0 dimensions*, although the should be handled as scalars rather than Datasets. This means that they cannot be stored (be a parameter of PUT and GET) and is not a mathematical function.

In general we also agree on allowing Datasets without 0 measures, though an implicit one should be considered.

**Comment by capacma** [comment]
another case of dataset with 0 dimensions:
suppose ds_bop is dataset with 3 dimensions (ref_area, partner, time) then the following expression has 0 dimensions (denotes exactly one row of the dataset) and it seems to be perfectly correct:
ds_bop [sub ref_area="IT",partner="US",time=2000]
for example:
ds_bop [sub ref_area="IT",partner="US",time=2000].obs_value
denotes the value of obs_value in the row specified by the above co-ordinates.
