### ISSUE TITLE
Ruleset artefact isn’t covered at all in User Manual document, only in Reference Manual.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#5]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-CSO-24|UM|84|825
PL-CSO-24|RM|31|825
***
Ruleset artefact isn’t covered at all in User Manual document, only in Reference Manual.	
Describe ruleset concept in User Manual.

**Comment by amattioc** [comment]
fixed in 2.0 manual
