### ISSUE TITLE
References to "expressions"

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#50]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
BDI-20|UM|49|All
BDI-20|RM|31|All
***

### Issue Description
Various references to the idea of "expressions", which are defined (page 31) inconsistently with the user manual.

### Proposed Solution
Concentrate these high-level aspects in the user manual and make the definitions coherent.

**Comment by linardian** [comment]
Notes regarding an old version of the documentation
