### ISSUE TITLE
Collaboration guidelines

### ISSUE THREAD

**Issue by romaintailhurat** [sdmx-twg/vtl#507]
Making Sense and Meaningful Data will help with providing content to the 2.1 documentation.

We still have to agree on how to do that.

What I propose is the following:

- every contributor fork the repository
- changes are made on forks and on a specific `dev` branch
- changes are then submitted as pull requests (PR)
- those PR are reviewed and accepted by a maintainer (Attilio, Angelo?)

This way, you can properly validate every contribution. What do you think?

**Comment by romaintailhurat** [comment]
@javihern98 you already created a https://github.com/sdmx-twg/vtl/tree/docs-dev, we probably use this one, but do you agree on the use of forks + PR?

**Comment by javihern98** [comment]
Hi @romaintailhurat, we are already pushing into the main repository, instead of a forked one, as we believe just adding specific branches will be necessary, instead of forking the whole project. We should only be concerned about placing the files in the specific directories, as with the current layout we should be able to just add the documentation and it will be automatically linked

**Comment by romaintailhurat** [comment]
I also provided a small setup guide, for now in a proper branch for agreement: https://github.com/sdmx-twg/vtl/blob/romain/v2.1/docs/README.md

**Comment by romaintailhurat** [comment]
> Hi @romaintailhurat, we are already pushing into the main repository, instead of a forked one, as we believe just adding specific branches will be necessary, instead of forking the whole project. We should only be concerned about placing the files in the specific directories, as with the current layout we should be able to just add the documentation and it will be automatically linked

Hi 👋 

I don't personally mind using only branches but using forks is a way to use PR which are a good and integrated way for Angelo or Attilio to validate changes.

So, ok for using feature branches.

I suggest at least to separate reference manual work from user manual, so using for example a `docs-dev/user-manual` for the latter.

What do you think @javihern98 @NicoLaval ?

**Comment by javihern98** [comment]
Yes, I agree. We will attempt to rename our branch to docs-dev/reference-manual

**Comment by romaintailhurat** [comment]
It wasn't possible to create `docs-dev/user-manual` because of the existence of `docs-dev`, so I just created a `docs-dev-um` for the user manual part. Feel free to mirror this naming or not. 😄

**Comment by amattioc** [comment]
The development phase of the new docs format has completed. Entering maintanance mode with PRs + reviews.
