### ISSUE TITLE
Concept of operator and function

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#53]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
BDI-2|UM|50|All
BDI-19|UM|50|All
***

### Issue Description
(BDI-2) Some term is used with different meanings in the two parts, in particular the term "function" in the former part refers to the functional link between the values of the identifiers and the values of the other variables of the data extension, while in the latter part refers to a property of the operators of the language (the functional link between the input and the output of the operator)

(BDI-19) There is some confusion between the concept of operator and function.

### Proposed Solution
(BDI-2) When the same term is used to mean different things, it is suggested either to distinguish the term (if possible and suitable) or to explain better the different meanings in which it is used. This comment is strictly related to the previous one.

(BDI-19) Clarify these aspects.

**Comment by bellomarini** [comment]
We suggest to rename *user define functions* into *user defined operators*.
