### ISSUE TITLE
Brackets used for the body of functions

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#54]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB2-6|UM|53|1825
ECB2-6|UM|32-52|827-1992
***

### Issue Description
It would be useful to harmonize the brackets used for the body of functions (see line 1992), datapoint ruleset (see line 827) and procedures (see part I, line 1825).

### Proposed Solution
Use for example {body} in all of them.

**Comment by bellomarini** [comment]
Agree with the proposed solution.

**Comment by capacma** [comment]
In the draft 1.1 the harmonised solution is to not use brackets. Instead, the **define** statements ( ruleset, function, dataset, etc.) is closed by **end**. Example:
define datapoint ruleset r  ( ... ) is
...
end datapoint ruleset 

define function f  ( ... ) is
...
end function

**Comment by bellomarini** [comment]
Proposed solution from the meeting
------------------------------------

Used curly brackets {body} everywhere. 
Please vote.
