### ISSUE TITLE
The "is" operator

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#55]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV-5|UM|60|2096
***

### Issue Description
The "is" operator is not mentioned in the reference manual.

### Proposed Solution
Should we include it in the reference manual with examples?

**Comment by dragan-ivanovic** [comment]
We should include it in the manual. The syntax should be:

<expression> `is` <type>

with sub-variant:

<expression> `is` `not` <type>

which is equivalent to:

`not`(<expression> `is` <type>)

In VTL 1.1 type system, `null` is a type (a subtype of `scalar`) which contains exactly one value, `null`.  Therefore `is null` is a special case for testing whether a scalar value is `null`, but the construct can be used more widely for performing arbitrary type checks.

**Comment by bellomarini** [comment]
Probably we should briefly discuss the **is** operator during next meeting.

**Comment by linardian** [comment]
Refers to old version of documentation
