### ISSUE TITLE
Designed with minimal redundancies

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#60]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-1|UM|9|247
***

### Issue Description
"Designed with minimal redundancies" seems to be at odds with the existence of postfix operators for filter, keep, etc. in addition to similar clauses within the join operator and allowing the join operator to be used with just one dataset for dataset traversal.

**Comment by capacma** [comment]
This issue is treated in #249
