### ISSUE TITLE
VTL information model

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#61]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-18|UM|19|VTL information model
***

### Issue Description
Review and update the information model for the VTL 1.1.

**Comment by capacma** [comment]
This issue is linked (not exclusively) to #46

**Comment by VincDV** [comment]
In the 21/14/2017 teleconference it was presented a proposal for the unified model of the Transformations aimed at unifying the representation of the Transformations in the VTL User Manual and in the SDMX implementation of the VTL.  The presented model at the moment is just a draft and needs to be enriched with all the details and further discussed in a more advanced version.  The presented model was agreed as a good starting point for developing the final model.   As a specific aspect of the model, it was discussed  and agreed that the core and the non-core operators of the VTL Standard Library do not need to be represented in different object classes of the class diagram.
