### ISSUE TITLE
The keyword "in"

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#65]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB2-7|UM|53|1825
***

### Issue Description
The keyword `in` in the procedure is used with a different meaning than `in` as a "comparator".

### Proposed Solution
`In` could be the default value in procedures and thus omitted.

**Comment by dragan-ivanovic** [comment]
While it is true that `in` is used in different contexts to mean different things, this is relatively common to the use of that reserved word in other languages as SQL.

However, removing it is also acceptable.
