### ISSUE TITLE
The “is” operator is of limited use while there is no conditional statements in VTL. 

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#68]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-CSO-11|UM|59|2094
***

### Issue Description
The “is” operator is of limited use while there is no conditional statements in VTL. 

### Proposed Solution
Provide some practical usage examples of “is” operator.

**Comment by linardian** [comment]
Notes on an old version of documentation
