### ISSUE TITLE
Rearrange the rows / columns in the classical way

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#69]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB-2|UM|64|2202
***

### Issue Description
We suggest to rearrange the rows / columns in the classical way 0 0, 0 1, 1, 0, 1 1

### Proposed Solution
See the Table in the original Word file

**Comment by linardian** [comment]
Refers to a previous version of the documentation
