### ISSUE TITLE
Order of execution and order of definition

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#7]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-13|UM|94|Vertical ruleset: order of execution
MC-13|RM|34|Vertical ruleset: order of execution
MC-15|UM/RM|94|Order of execution of statements
***

### Issue Description
Order of execution: Order of definition,Computed by VTL.
Order of execution of the statements in a VTL program: Order of definition,Computed by VTL
The general behaviour of operations on datasets is not aligned with the reference manual (see table page 13)

### Initially Proposed Solution
Parameter to choose between 2 modes?
See 23 (is this MC-23? to be linked to GitHub issue)

### Proposed Solution

*Based on the discussions in the teleconference on 2017-02-16.*

#### Background

In it simplest form, a VTL statement has the *transformation form* `V:= E`, where `V` is a variable name, and `E` is an expression.  It computes the value of expression `E` and gives the result name `V`.  Variables are immutable in VTL, in the sense that once a variable is assigned a value, it cannot be re-assigned.  Aside of transformations, VTL also includes some other kinds of statements (typically starting with keyword `define`), but their meaning can always be described as creating a named object of a certain kind (a function, a dataset, a rule, etc.).

#### Contexts in which transformations can appear

A transformation can appear in one of two possible contexts:

- **Source code:** VTL transformations are written one after another in the source code of a VTL program or module, or inside the body of a user-defined function.  The order in which the programmer writes the statements in the source file expresses the intended meaning of the program.

- **Transformation scheme:** Each VTL transformation is separately represented (documented or displayed), and may be equipped with comments, explanations, and other metadata for the end-user.  A group of transformations is called a transformation scheme.  Depending on the presentation format for the end user, the transformations in a scheme can be displayed in different order (or not linearly at all).

#### Order of execution

In order for a transformation `V := E` to be executable, the values of all variables appearing in `E` must be already known.  (This also applies to other named objects used in `E`, such as the user-defined functions.)  This induces a directed dependency graph where one statement `V := E` depends on another statement `W := F` if (and only if) `W` is used in `E`.  This dependency graph must be acyclic: any cyclic dependence is treated as an error.

The existence of a directed acyclic dependency graph between individual statements implies that the result of a series of transformations is deterministic:

- Each statement can start executing as soon as all of its dependencies have been executed.
- Two or more transformations that are mutually independent (directly or transitively) can execute concurrently if the execution platform has the concurrent computation capabilities.
- The dependency graph can be linearised by listing statements one after another so that each subsequent statement depends only on the results of the preceding it.
- Whether the execution of a set of statements is concurrent or linear does not affect the result, it only affects the efficiency of computation.

**Example 1** For instance, statements:

```
D1 := 2*D2+1 // Statement S1
```

and 

```
D2 := (D1-1)/2 // Statement S2
```

form a circular dependence on each other, and therefore cannot be executed.

**Example 2** The following statements (not necessarily written in the
  given order):

```
D1 := 1/(1-D0)  // Statement S1
D2 := 2*D0+1    // Statement S2
D3 := D1 + D0   // Statement S3
D4 := D3 / D2   // Statement S4
```

form an acyclic graph:

```
S1 -- S3 
       \
S2 ---- S4
```

When executing, the two independent statements, S1 and S2, can execute concurrently.  S3 must wait for S1, and S4 must wait for both S2 and S3.

This example can be linerised in three ways:

- `S1-S2-S3-S4`,
- `S1-S3-S2-S4`, and
- `S2-S1-S3-S4`.

In all cases the result must be the same.

#### Solution for the source code context ####

In a source code context, by the nature of a text file, transformations are already given in a linearised form controlled by the programmer.  That linearised form must be correct in the sense that each statement must not use variables computed by the statements following it in the text.  If a preceding statement tries to use a variable assigned in a later statement, an error must be raised.  This can draw the programmer's attention to possible errors in validation and transformation programs, and require a tighter programming discipline to ensure the program correctness.

In such a context, the execution of transformation can be sequential, following the order in which they are written, but does not necessarily need to be such.  Instead, VTL implementations can analyse dependencies and execute mutually independent transformations concurrently, thus increasing efficiency.  However, the result of the computation must be the same.

#### Solution for the transformation scheme context ####

In a transformation scheme, the ordering of transformations may not be strict.  Instead of being tightly coupled in a single source code file, individual transformations are typically individually represented in a persistent store, can be maintained and documented by different persons, and are much more loosely coupled with each other.  In fact, the same transformation can, in principle, be a member of several transformation schemes at the same time.

Therefore it is reasonable not to impose any strict requirement on the order in which transformations in a transformation scheme are presented (shown to the user).  Rather, it is up to the VTL implementation to check that a transformation schemes are correct in the sense that they do not induce any cyclic dependence between different transformations, before trying to execute them.

As in the source code case, the VTL implementations are free to choose the execution strategy, as long as it is consistent with the dependency graph and ensuring that the result is the same.

**Comment by bellomarini** [comment]
In my opinion, the order of execution should be not relevant and the result of the program in terms of calculated Datasets should be the same, independently of the order. 

Clearly, since the various statements are related to one another, the VTL runtime system will be responsible for choosing an appropriate execution sequence. Yet, multiple different execution sequences can exist (all correct, but different indeed) and the user should not be aware of which one is chosen.

This concept is quite usual in declarative languages and particularly straightforward to apply in VTL since we do not have recursion, which means that there cannot be circular dependencies among the rules.

For example, consider the following VTL program (where line numbers are not part of the syntax):

```
1: d1 := d2 + d3
2: d4 := d1 + d5
3: d7 := d1 + d6
```
possible execution orders are: 1,2,3; 1,3,2. They are both correct since we only have the following dependencies (1 -> 2 and 1-> 3).  More precisely, the execution sequence of a program may be any topological sort of the dependencies.

I have not preclusions wrt an optional parameter to control the runtime behavior, but it seems to be superfluous.

**Comment by linardian** [comment]
Notes on obsolete version of documentation
