### ISSUE TITLE
Explicit/implicit component computations

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#71]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-CSO-13|UM|70|2370
***

### Issue Description
Purpose of explicit/implicit component computations is unclear. If working record of implicit computation contains component X with the same role then no computation is performed and no error raised. It might be misleading and unintuitive.

### Solution Proposed in the Issue Submission 
With implicit computation raise error if there is already a component named X, even with the same role. Optionally change the default behaviour to forbid overriding components. This could be performed by adding “override” keyword that strictly forces replacement of existing and raise error when X does not already exist.

### Discussed Solution
Keep the mechanism as it currently is in the documentation. If necessary reword and include examples.

**Comment by linardian** [comment]
Refers to an old version of documentation.
