### ISSUE TITLE
“E is not a string expression and it evaluates to null”. This sentence does not make sense.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#73]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-2|UM|69|2346
SN-4|UM|70|2375
***

### Issue Description
“E is not a string expression and it evaluates to null”. This sentence does not make sense.

### Proposed Solution
Correct sentence to clarify what is meant.

**Comment by linardian** [comment]
Refers to a previous version of the documentation
