### ISSUE TITLE
The constructs “unfold using” and “fold using” are not specified in the Reference Manual.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#75]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-6|UM|74|2512
***

### Issue Description
The constructs “unfold using” and “fold using” are not specified in the Reference Manual.

### Proposed Solution
Create reference specifications of “unfold using” and “fold using”

**Comment by capacma** [comment]
Maybe the feature "**unfold** X, Y **using** H" (i.e., using a hierarchy) can be removed
