### ISSUE TITLE
No core mechanism for aggregations. 

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#76]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-GOV-1|UM|74|2509
***

### Issue Description
There is no core mechanism for aggregations. Only sum aggregation can be calculated by unfold statement in limited cases.

### Proposed Solution
Mark all aggregates as core functions. Optionally add new universal aggregating mechanism to the core (or modify existing one), so all aggregate functions of standard library could be described using core.

**Comment by dragan-ivanovic** [comment]
A natural place to integrate the aggregation operators in the language core is in the FLWOR statements.

**Comment by linardian** [comment]
Refers to old version of documentation
