### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#79]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB-7|UM|90|3030
***

### Issue Description
The table “Dr = European Countries / Europe * 100” contains values in the column “Ref. Date” which are not contained in the input tables “D1 = European Countries” or “D2 = Europe”

**Comment by linardian** [comment]
Corrected in the current live versione
