### ISSUE TITLE
Missing data and NULL management

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#8]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
BDI-13|UM/RM|95|All
BDI-22|UM/RM|95|All
MC-11|UM/RM|95|Missing data
***
Combination of datasets where different combinations of keys are present. Assume a certain key exists in one dataset and not in the other. What are the supported options? assume the key as existing with a 0 value measure; assume the key existing with a null value measure; others? The assumed behavior is not clear and seem to be operator-based.
NULL management is often defined with an ad hoc approach in each operator and it seems not aligned with the User Manual.
Approach described in the chapter "missing data" to be integrated in the chapter on the core?

**Comment by bellomarini** [comment]
* The agreement is to adopt **explicit zeros**. If any row is missing one of the operands, it does not appear in the output. This corresponds to the semantics of the *inner join*.

* We cancelled the explicit zeros.

* Possible *null* values combine according to the usual algebraic rules.

* **listsum** is useful to handle implicit cases.

* See #45
