### ISSUE TITLE
Typo in expression

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#81]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-GOV-5|UM|96|3265
***

### Issue Description
Dr := D1 [M1 := if M1 is null then 1 else M1] * D2

### Proposed Solution
Dr := [D1]{M1 := if M1 is null then 1 else M1} * D2

**Comment by bellomarini** [comment]
It is already solved like this in the harmonized version of the clauses-join discussed during the meeting (see also #340).
