### ISSUE TITLE
Slash symbol, double meaning in persistent data set.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#82]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-CSO-18|UM|103|3510, 3549
***

### Issue Description
Slash symbol has double meaning in persistent data set id. For example id “NAME/USA” might mean both: dataset USA in namespace NAME, dataset NAME filtered by USA

### Proposed Solution
Change filter separator sign in persistent DS Id . Optionally recommend another namespace separator.

**Comment by linardian** [comment]
Refers to an old version of documentation.
