### ISSUE TITLE
Behaviour of using “put”.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#83]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-GOV-3|UM|101|3433
***

### Issue Description
Behaviour of using “put” operator multiple times for the same persistent dataset is undefined. Example illustrating the problem: A := put(X, “DS1”)  B := put(Y, “DS1”)

### Proposed Solution
Explicitly forbid using “put” operator multiple times with the same persistent dataset id.

**Comment by capacma** [comment]
How to check that put is not used with the same dataset id? The second operand of put is a string, that normally means that its value is known only at run time.

**Comment by linardian** [comment]
Refers to a previous version of the documentation
