### ISSUE TITLE
The sentence: For   this   reason,   the   VTL   requires   that   at compilation time the Data Structures of the referenced Data Sets are available. 

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#84]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV-10|UM|102|3474
***

### Issue Description
The sentence: For   this   reason,   the   VTL   requires   that   at compilation time the Data Structures of the referenced Data Sets are available. Is not very clear to me. 

### Proposed Solution
Clarify how VTL can manage this.

**Comment by capacma** [comment]
Alternative: drop the following sentence at page 102:
For this reason, the VTL requires that at compilation time the Data Structures of the referenced Data Sets are available.

**Comment by linardian** [comment]
Refers to old version of documentation
