### ISSUE TITLE
Incomplete List of Reserved Keywords.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#85]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-CSO-19|UM|103|3584
***

### Issue Description
List of reserved keywords is incomplete. Keywords new in VTL 1.1 not included. 

### Proposed Solution
Include missing keywords. Sign ‘.’ Should take place of ‘#’.
Split the types of keywords on those that are strictly reserved for VTL and those that may be allowed to be used in different contexts.

**Comment by linardian** [comment]
Refers to old version of documentation,
