### ISSUE TITLE
Complexity of Ranged value domain.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#88]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MTNA-13|UM| |1512
***

### Issue Description
Ranged value domain may be more complex than a single range.

### Proposed Solution
Add support for compound.complex range sets like [1,2,3,10:50,>99]. Could also apply to non-integral values.

**Comment by VincDV** [comment]
In the today teleconference (21/04/2017) it was agreed to accept the comment only if the solution is very easy to implement, otherwise to postpone the issue after the VTL 1.1 release, to a following milestone.

**Comment by linardian** [comment]
Refers to old version of documentation
