### ISSUE TITLE
There is no support for the concept of a time span, and a lack of date manipulation and comparison functions.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#90]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MTNA-7|UM| |2907
***

### Issue Description
There is no support for the concept of a time span, and a lack of date manipulation and comparison functions.

### Proposed Solution
Add support for Time spans or other date time manipulation operators.

**Comment by linardian** [comment]
New time operators are going to be added
