### ISSUE TITLE
Timezone not supported in Date type.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#92]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MTNA-9|UM| |2907
***

### Issue Description
Timezone does not seem to be supported in Date type.

### Proposed Solution
Add support for time zone or simply align date/time on ISO 8601 (which also provides specifications for time period).

**Comment by linardian** [comment]
Refers to old version of documentation
