### ISSUE TITLE
There no support for an explicit arbitrary precision "decimal" like data type whereby a precise number of digits can be specified.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#93]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MTNA-10|UM| |2907
***

### Issue Description
There no support for an explicit arbitrary precision "decimal" like data type whereby a precise number of digits can be specified.

### Proposed Solution
Add a Decimal data type

**Comment by linardian** [comment]
Refers to old version of documentation
