### ISSUE TITLE
No support for non-NULL missing values. Missing data can be much more than NULL.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#94]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MTNA-5|UM| |3192
***

### Issue Description
No support for non-NULL missing values. Missing data can be much more than NULL.

### Proposed Solution
Most stats packages have predefined missing categories (e.g Stata .a-z) or (SPSS') customizable flagging of values as missing. Highly desirable. Latter option preferable.

**Comment by linardian** [comment]
Refers to old version of documentation
