### ISSUE TITLE
The text seems to use “&” as a string concatenation operator.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#95]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-5|UM|72-73|2434 - 2451
***

### Issue Description
The text seems to use “&” as a string concatenation operator.

### Proposed Solution
Replace with the correct string concatenation operator “||”

**Comment by linardian** [comment]
Refers to a previous version of the documentation
