### ISSUE TITLE
Postfix rename syntax “[Value->InRange]” 

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#96]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-8|UM|80-93-94|2707 - 3150 - 3164
***

### Issue Description
The postfix rename syntax “[Value->InRange]” does not seem to be documented anywhere else.

### Proposed Solution
Document this syntax or replace with correct syntax.

**Comment by linardian** [comment]
Refers to old version of documentation,
