### ISSUE TITLE
VTL Code - Paste Function

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#97]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
SN-9|UM|83-84|2850 - 2853 - 2856
***

### Issue Description
The VTL code uses the function “paste” which is not defined anywhere.

### Proposed Solution
Document paste function or replace with documented function.

**Comment by linardian** [comment]
Refers to a previous version of the documentation
