### ISSUE TITLE
Iterations

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#99]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB2-1|UM||
***

### Issue Description
Iterations (see document "Iteration problem using VTL.docx")

### Proposed Solution
I have received from Luigi a possible solution to the iteration problem. However, I keep this entry here because there are some points that are not clear to us.

**Comment by bellomarini** [comment]
see #83

**Comment by linardian** [comment]
Refers to old version of documentation,
